; Generated by C→R316 compiler
%include "common"

; ── entry point ──
start:
    mov r30, 0x800
    jmp r31, __term_init
    jmp r31, main
    hlt

    ; function main
main:
    sub r30, 2
    st r31, r30, 1
    mov r5, _cstr_1
    mov r1, r5
    jmp r31, puts
    mov r6, r1
    mov r5, 1
    st r5, r30, 0
._c2r_fcond_2:
    ld r6, r30, 0
    mov r7, 10
    sub r0, r6, r7
    jle ._c2r_ct_5
    mov r6, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r6, 1
._c2r_ce_6:
    test r6, r6
    jz ._c2r_fend_4
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    mov r5, 10
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_fstep_3:
    mov r7, r30
    ld r8, r7
    mov r9, r8
    add r9, 1
    st r9, r7
    jmp ._c2r_fcond_2
._c2r_fend_4:
    mov r5, 0
    mov r1, r5
    jmp main._ret
main._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31


; ── string literals ──
_cstr_1: dw 72, 101, 108, 108, 111, 44, 32, 82, 51, 49, 54, 33, 0

; ── runtime library ──
%include "runtime.asm"
