; Generated by C→R316 compiler
%include "common"

; ── entry point ──
start:
    mov r30, 0x800
    jmp r31, __term_init
    jmp r31, main
    hlt

    ; function main
main:
    sub r30, 2
    st r31, r30, 1
    mov r5, _cstr_1
    mov r1, r5
    jmp r31, printf
    mov r6, r1
    mov r5, 1
    st r5, r30, 0
._c2r_fcond_2:
    ld r6, r30, 0
    mov r7, 10
    sub r0, r6, r7
    jle ._c2r_ct_5
    mov r6, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r6, 1
._c2r_ce_6:
    test r6, r6
    jz ._c2r_fend_4
    mov r5, _cstr_7
    ld r6, r30, 0
    sub r30, 1
    st r6, r30, 0
    mov r1, r5
    jmp r31, printf
    add r30, 1
    mov r7, r1
._c2r_fstep_3:
    mov r8, r30
    ld r9, r8
    mov r10, r9
    add r10, 1
    st r10, r8
    jmp ._c2r_fcond_2
._c2r_fend_4:
    mov r5, 0
    mov r1, r5
    jmp main._ret
main._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31


; ── string literals ──
_cstr_1: dw 72, 101, 108, 108, 111, 44, 32, 82, 51, 49, 54, 33, 0
_cstr_7: dw 86, 97, 108, 117, 101, 58, 37, 100, 10, 0

; ── runtime library (compiled from runtime.c) ──
    ; function _print_digits
_print_digits:
    sub r30, 4
    st r31, r30, 3
    st r1, r30, 2
    ld r5, r30, 2
    mov r6, 10
    mov r1, r5
    mov r2, r6
    jmp r31, __udiv
    mov r7, r1
    st r7, r30, 0
    ld r5, r30, 2
    mov r6, 10
    mov r1, r5
    mov r2, r6
    jmp r31, __umod
    mov r7, r1
    st r7, r30, 1
    ld r5, r30, 0
    test r5, r5
    jz ._c2r_else_1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, _print_digits
    mov r6, r1
._c2r_else_1:
    mov r5, 48
    ld r6, r30, 1
    add r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
_print_digits._ret:
    ld r31, r30, 3
    add r30, 4
    jmp r31

    ; function print_uint
print_uint:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 0
    sub r0, r5, r6
    jz ._c2r_ct_5
    mov r5, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r5, 1
._c2r_ce_6:
    test r5, r5
    jz ._c2r_else_3
    mov r5, 48
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp print_uint._ret
._c2r_else_3:
    ld r5, r30, 0
    mov r1, r5
    jmp r31, _print_digits
    mov r6, r1
print_uint._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function print_int
print_int:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 0
    sub r0, r5, r6
    jl ._c2r_ct_9
    mov r5, 0
    jmp ._c2r_ce_10
._c2r_ct_9:
    mov r5, 1
._c2r_ce_10:
    test r5, r5
    jz ._c2r_else_7
    mov r5, 45
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    ld r5, r30, 0
    sub r5, r0, r5
    st r5, r30, 0
._c2r_else_7:
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_uint
    mov r6, r1
print_int._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function print_hex
print_hex:
    sub r30, 4
    st r31, r30, 3
    st r1, r30, 2
    mov r5, 0
    st r5, r30, 0
._c2r_fcond_11:
    ld r6, r30, 0
    mov r7, 4
    sub r0, r6, r7
    jl ._c2r_ct_14
    mov r6, 0
    jmp ._c2r_ce_15
._c2r_ct_14:
    mov r6, 1
._c2r_ce_15:
    test r6, r6
    jz ._c2r_fend_13
    ld r5, r30, 2
    mov r6, 12
    shr r5, r6
    mov r6, 15
    and r5, r6
    st r5, r30, 1
    ld r5, r30, 1
    mov r6, 10
    sub r0, r5, r6
    jnl ._c2r_ct_18
    mov r5, 0
    jmp ._c2r_ce_19
._c2r_ct_18:
    mov r5, 1
._c2r_ce_19:
    test r5, r5
    jz ._c2r_else_16
    mov r5, 65
    ld r6, r30, 1
    add r5, r6
    mov r6, 10
    sub r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_endif_17
._c2r_else_16:
    mov r5, 48
    ld r6, r30, 1
    add r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_endif_17:
    ld r5, r30, 2
    mov r6, 4
    shl r5, r6
    st r5, r30, 2
._c2r_fstep_12:
    mov r6, r30
    ld r7, r6
    mov r8, r7
    add r8, 1
    st r8, r6
    jmp ._c2r_fcond_11
._c2r_fend_13:
print_hex._ret:
    ld r31, r30, 3
    add r30, 4
    jmp r31

    ; function print_str
print_str:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
._c2r_wcond_20:
    ld r5, r30, 0
    ld r5, r5
    test r5, r5
    jz ._c2r_wend_22
    ld r5, r30, 0
    ld r5, r5
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_20
._c2r_wend_22:
print_str._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function puts
puts:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    mov r5, 10
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
puts._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function strlen
strlen:
    sub r30, 2
    st r1, r30, 1
    mov r5, 0
    st r5, r30, 0
._c2r_wcond_23:
    ld r5, r30, 1
    ld r5, r5
    test r5, r5
    jz ._c2r_wend_25
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_23
._c2r_wend_25:
    ld r5, r30, 0
    mov r1, r5
    jmp strlen._ret
strlen._ret:
    add r30, 2
    jmp r31

    ; function strcmp
strcmp:
    sub r30, 2
    st r1, r30, 0
    st r2, r30, 1
._c2r_wcond_26:
    ld r6, r30, 0
    ld r6, r6
    mov r5, r6
    test r5, r5
    jz ._c2r_sc_29
    ld r6, r30, 0
    ld r6, r6
    ld r7, r30, 1
    ld r7, r7
    sub r0, r6, r7
    jz ._c2r_ct_30
    mov r6, 0
    jmp ._c2r_ce_31
._c2r_ct_30:
    mov r6, 1
._c2r_ce_31:
    mov r5, r6
._c2r_sc_29:
    test r5, r5
    jnz ._c2r_sct_32
    mov r5, 0
    jmp ._c2r_sce_33
._c2r_sct_32:
    mov r5, 1
._c2r_sce_33:
    test r5, r5
    jz ._c2r_wend_28
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_26
._c2r_wend_28:
    ld r5, r30, 0
    ld r5, r5
    ld r6, r30, 1
    ld r6, r6
    sub r5, r6
    mov r1, r5
    jmp strcmp._ret
strcmp._ret:
    add r30, 2
    jmp r31

    ; function memset
memset:
    sub r30, 3
    st r1, r30, 0
    st r2, r30, 1
    st r3, r30, 2
._c2r_wcond_34:
    ld r5, r30, 2
    mov r6, 0
    sub r0, r5, r6
    jnle ._c2r_ct_37
    mov r5, 0
    jmp ._c2r_ce_38
._c2r_ct_37:
    mov r5, 1
._c2r_ce_38:
    test r5, r5
    jz ._c2r_wend_36
    ld r5, r30, 1
    ld r6, r30, 0
    st r5, r6
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 2
    ld r6, r5
    mov r7, r6
    sub r7, 1
    st r7, r5
    jmp ._c2r_wcond_34
._c2r_wend_36:
memset._ret:
    add r30, 3
    jmp r31

    ; function memcpy
memcpy:
    sub r30, 3
    st r1, r30, 0
    st r2, r30, 1
    st r3, r30, 2
._c2r_wcond_39:
    ld r5, r30, 2
    mov r6, 0
    sub r0, r5, r6
    jnle ._c2r_ct_42
    mov r5, 0
    jmp ._c2r_ce_43
._c2r_ct_42:
    mov r5, 1
._c2r_ce_43:
    test r5, r5
    jz ._c2r_wend_41
    ld r5, r30, 1
    ld r5, r5
    ld r6, r30, 0
    st r5, r6
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 2
    ld r6, r5
    mov r7, r6
    sub r7, 1
    st r7, r5
    jmp ._c2r_wcond_39
._c2r_wend_41:
memcpy._ret:
    add r30, 3
    jmp r31

    ; function printf
printf:
    sub r30, 6
    st r31, r30, 5
    st r1, r30, 4
    mov r5, r30
    add r6, r30, 6
    st r6, r5
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
._c2r_wcond_44:
    ld r5, r30, 1
    test r5, r5
    jz ._c2r_wend_46
    ld r5, r30, 1
    mov r6, 37
    sub r0, r5, r6
    jz ._c2r_ct_49
    mov r5, 0
    jmp ._c2r_ce_50
._c2r_ct_49:
    mov r5, 1
._c2r_ce_50:
    test r5, r5
    jz ._c2r_else_47
    ld r5, r30, 4
    mov r6, 1
    add r5, r6
    st r5, r30, 4
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
    ld r5, r30, 1
    mov r6, 100
    sub r0, r5, r6
    jz ._c2r_ct_53
    mov r5, 0
    jmp ._c2r_ce_54
._c2r_ct_53:
    mov r5, 1
._c2r_ce_54:
    test r5, r5
    jz ._c2r_else_51
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp ._c2r_endif_52
._c2r_else_51:
    ld r5, r30, 1
    mov r6, 117
    sub r0, r5, r6
    jz ._c2r_ct_57
    mov r5, 0
    jmp ._c2r_ce_58
._c2r_ct_57:
    mov r5, 1
._c2r_ce_58:
    test r5, r5
    jz ._c2r_else_55
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_uint
    mov r6, r1
    jmp ._c2r_endif_56
._c2r_else_55:
    ld r5, r30, 1
    mov r6, 120
    sub r0, r5, r6
    jz ._c2r_ct_61
    mov r5, 0
    jmp ._c2r_ce_62
._c2r_ct_61:
    mov r5, 1
._c2r_ce_62:
    test r5, r5
    jz ._c2r_else_59
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_hex
    mov r6, r1
    jmp ._c2r_endif_60
._c2r_else_59:
    ld r5, r30, 1
    mov r6, 115
    sub r0, r5, r6
    jz ._c2r_ct_65
    mov r5, 0
    jmp ._c2r_ce_66
._c2r_ct_65:
    mov r5, 1
._c2r_ce_66:
    test r5, r5
    jz ._c2r_else_63
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 3
    ld r5, r30, 3
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp ._c2r_endif_64
._c2r_else_63:
    ld r5, r30, 1
    mov r6, 99
    sub r0, r5, r6
    jz ._c2r_ct_69
    mov r5, 0
    jmp ._c2r_ce_70
._c2r_ct_69:
    mov r5, 1
._c2r_ce_70:
    test r5, r5
    jz ._c2r_else_67
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_endif_68
._c2r_else_67:
    ld r5, r30, 1
    mov r6, 37
    sub r0, r5, r6
    jz ._c2r_ct_73
    mov r5, 0
    jmp ._c2r_ce_74
._c2r_ct_73:
    mov r5, 1
._c2r_ce_74:
    test r5, r5
    jz ._c2r_else_71
    mov r5, 37
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_else_71:
._c2r_endif_68:
._c2r_endif_64:
._c2r_endif_60:
._c2r_endif_56:
._c2r_endif_52:
    jmp ._c2r_endif_48
._c2r_else_47:
    ld r5, r30, 1
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_endif_48:
    ld r5, r30, 4
    mov r6, 1
    add r5, r6
    st r5, r30, 4
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
    jmp ._c2r_wcond_44
._c2r_wend_46:
printf._ret:
    ld r31, r30, 5
    add r30, 6
    jmp r31


; ── runtime core (asm) ──
%include "runtime_core.asm"
