; Generated by C→R316 compiler
%include "common"

; ── entry point ──
start:
    mov r30, 0x800
    jmp r31, __term_init
    jmp r31, main
    hlt

    ; function newline
newline:
    sub r30, 1
    st r31, r30, 0
    mov r5, 10
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
newline._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function print_label
print_label:
    sub r30, 1
    st r31, r30, 0
    jmp r31, print_str
    mov r5, r1
    mov r5, _cstr_1
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
print_label._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function print_ok
print_ok:
    sub r30, 1
    st r31, r30, 0
    mov r5, _cstr_2
    mov r1, r5
    jmp r31, puts
    mov r6, r1
print_ok._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function factorial
factorial:
    sub r30, 1
    st r31, r30, 0
    mov r5, 1
    sub r0, r1, r5
    jle ._c2r_ct_5
    mov r1, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r1, 1
._c2r_ce_6:
    test r1, r1
    jz ._c2r_else_3
    mov r5, 1
    mov r1, r5
    jmp factorial._ret
._c2r_else_3:
    mov r5, 1
    sub r1, r5
    jmp r31, factorial
    mov r5, r1
    mul r1, r1, r5
    jmp factorial._ret
factorial._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function fib
fib:
    sub r30, 1
    st r31, r30, 0
    mov r5, 1
    sub r0, r1, r5
    jle ._c2r_ct_9
    mov r1, 0
    jmp ._c2r_ce_10
._c2r_ct_9:
    mov r1, 1
._c2r_ce_10:
    test r1, r1
    jz ._c2r_else_7
    jmp fib._ret
._c2r_else_7:
    mov r5, 1
    sub r1, r5
    jmp r31, fib
    mov r5, r1
    mov r6, 2
    sub r1, r6
    jmp r31, fib
    mov r6, r1
    add r5, r6
    mov r1, r5
    jmp fib._ret
fib._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function array_sum
array_sum:
    sub r30, 2
    mov r5, 0
    st r5, r30, 1
    mov r5, 0
    st r5, r30, 0
._c2r_fcond_11:
    ld r6, r30, 0
    sub r0, r6, r2
    jl ._c2r_ct_14
    mov r6, 0
    jmp ._c2r_ce_15
._c2r_ct_14:
    mov r6, 1
._c2r_ce_15:
    test r6, r6
    jz ._c2r_fend_13
    ld r5, r30, 1
    ld r6, r30, 0
    add r1, r6
    ld r1, r1
    add r5, r1
    st r5, r30, 1
._c2r_fstep_12:
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_fcond_11
._c2r_fend_13:
    ld r5, r30, 1
    mov r1, r5
    jmp array_sum._ret
array_sum._ret:
    add r30, 2
    jmp r31

    ; function swap
swap:
    sub r30, 1
    ld r1, r1
    st r1, r30, 0
    ld r2, r2
    st r2, r1
    ld r5, r30, 0
    st r5, r2
swap._ret:
    add r30, 1
    jmp r31

    ; function main
main:
    sub r30, 16
    st r31, r30, 15
    mov r5, _cstr_16
    mov r1, r5
    jmp r31, puts
    mov r6, r1
    mov r5, _cstr_17
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 4
    add r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_18
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 10
    mov r6, 3
    sub r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_19
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 6
    mov r6, 7
    mul r5, r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_20
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 20
    mov r6, 4
    mov r1, r5
    mov r2, r6
    jmp r31, __udiv
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_21
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 17
    mov r6, 5
    mov r1, r5
    mov r2, r6
    jmp r31, __umod
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_22
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    and r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_23
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    or  r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_24
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    xor r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_25
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 0
    xor r5, 0xFFFF
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_26
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 1
    mov r6, 4
    shl r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_27
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 32
    mov r6, 2
    shr r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_28
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 3
    sub r0, r5, r6
    jz ._c2r_ct_29
    mov r5, 0
    jmp ._c2r_ce_30
._c2r_ct_29:
    mov r5, 1
._c2r_ce_30:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_31
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 4
    sub r0, r5, r6
    jnz ._c2r_ct_32
    mov r5, 0
    jmp ._c2r_ce_33
._c2r_ct_32:
    mov r5, 1
._c2r_ce_33:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_34
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 2
    mov r6, 5
    sub r0, r5, r6
    jl ._c2r_ct_35
    mov r5, 0
    jmp ._c2r_ce_36
._c2r_ct_35:
    mov r5, 1
._c2r_ce_36:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_37
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 2
    sub r0, r5, r6
    jnl ._c2r_ct_38
    mov r5, 0
    jmp ._c2r_ce_39
._c2r_ct_38:
    mov r5, 1
._c2r_ce_39:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_40
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r6, 1
    mov r5, r6
    test r5, r5
    jz ._c2r_sc_41
    mov r6, 1
    mov r5, r6
._c2r_sc_41:
    test r5, r5
    jnz ._c2r_sct_42
    mov r5, 0
    jmp ._c2r_sce_43
._c2r_sct_42:
    mov r5, 1
._c2r_sce_43:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_44
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r6, 0
    mov r5, r6
    test r5, r5
    jnz ._c2r_sc_45
    mov r6, 1
    mov r5, r6
._c2r_sc_45:
    test r5, r5
    jnz ._c2r_sct_46
    mov r5, 0
    jmp ._c2r_sce_47
._c2r_sct_46:
    mov r5, 1
._c2r_sce_47:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_48
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 0
    test r5, r5
    jz ._c2r_nt_49
    mov r5, 0
    jmp ._c2r_ne_50
._c2r_nt_49:
    mov r5, 1
._c2r_ne_50:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 10
    st r5, r30, 0
    ld r5, r30, 0
    mov r6, 5
    add r5, r6
    st r5, r30, 0
    mov r5, _cstr_51
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 3
    sub r5, r6
    st r5, r30, 0
    mov r5, _cstr_52
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 2
    mul r5, r5, r6
    st r5, r30, 0
    mov r5, _cstr_53
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 4
    mov r1, r5
    mov r2, r6
    jmp r31, __udiv
    mov r5, r1
    st r5, r30, 0
    mov r5, _cstr_54
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 5
    and r5, r6
    st r5, r30, 0
    mov r5, _cstr_55
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 8
    or r5, r6
    st r5, r30, 0
    mov r5, _cstr_56
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 3
    xor r5, r6
    st r5, r30, 0
    mov r5, _cstr_57
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 5
    st r5, r30, 1
    mov r5, _cstr_58
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    add r6, 1
    st r6, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_59
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_60
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 1
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_61
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    sub r6, 1
    st r6, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 7
    st r5, r30, 2
    ld r5, r30, 2
    mov r6, 5
    sub r0, r5, r6
    jnl ._c2r_ct_64
    mov r5, 0
    jmp ._c2r_ce_65
._c2r_ct_64:
    mov r5, 1
._c2r_ce_65:
    test r5, r5
    jz ._c2r_else_62
    mov r5, _cstr_66
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    jmp ._c2r_endif_63
._c2r_else_62:
    mov r5, _cstr_67
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp r31, newline
    mov r5, r1
._c2r_endif_63:
    mov r5, 0
    st r5, r30, 3
    mov r5, _cstr_68
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
._c2r_wcond_69:
    ld r5, r30, 3
    mov r6, 10
    sub r0, r5, r6
    jl ._c2r_ct_72
    mov r5, 0
    jmp ._c2r_ce_73
._c2r_ct_72:
    mov r5, 1
._c2r_ce_73:
    test r5, r5
    jz ._c2r_wend_71
    add r5, r30, 3
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    ld r5, r30, 3
    mov r6, 3
    sub r0, r5, r6
    jz ._c2r_ct_76
    mov r5, 0
    jmp ._c2r_ce_77
._c2r_ct_76:
    mov r5, 1
._c2r_ce_77:
    test r5, r5
    jz ._c2r_else_74
    jmp ._c2r_wcond_69
._c2r_else_74:
    ld r5, r30, 3
    mov r6, 7
    sub r0, r5, r6
    jz ._c2r_ct_80
    mov r5, 0
    jmp ._c2r_ce_81
._c2r_ct_80:
    mov r5, 1
._c2r_ce_81:
    test r5, r5
    jz ._c2r_else_78
    jmp ._c2r_wend_71
._c2r_else_78:
    ld r5, r30, 3
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    mov r5, 32
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_wcond_69
._c2r_wend_71:
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_82
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    mov r5, 0
    st r5, r30, 4
._c2r_fcond_83:
    ld r6, r30, 4
    mov r7, 5
    sub r0, r6, r7
    jl ._c2r_ct_86
    mov r6, 0
    jmp ._c2r_ce_87
._c2r_ct_86:
    mov r6, 1
._c2r_ce_87:
    test r6, r6
    jz ._c2r_fend_85
    ld r5, r30, 4
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    mov r5, 32
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_fstep_84:
    add r7, r30, 4
    ld r8, r7
    mov r9, r8
    add r9, 1
    st r9, r7
    jmp ._c2r_fcond_83
._c2r_fend_85:
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_88
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r1, r5
    jmp r31, factorial
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_89
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 7
    mov r1, r5
    jmp r31, fib
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 10
    ld r6, r30, 5
    mov r7, 0
    add r6, r7
    st r5, r6
    mov r5, 20
    ld r6, r30, 5
    mov r7, 1
    add r6, r7
    st r5, r6
    mov r5, 30
    ld r6, r30, 5
    mov r7, 2
    add r6, r7
    st r5, r6
    mov r5, 40
    ld r6, r30, 5
    mov r7, 3
    add r6, r7
    st r5, r6
    mov r5, 50
    ld r6, r30, 5
    mov r7, 4
    add r6, r7
    st r5, r6
    mov r5, _cstr_90
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 5
    mov r1, r5
    mov r6, 5
    mov r2, r6
    jmp r31, array_sum
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r8, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 11
    st r5, r30, 10
    mov r5, 22
    st r5, r30, 11
    add r5, r30, 10
    mov r1, r5
    add r6, r30, 11
    mov r2, r6
    jmp r31, swap
    mov r7, r1
    mov r5, _cstr_91
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 10
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_92
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 11
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_93
    st r5, r30, 12
    mov r5, _cstr_94
    st r5, r30, 13
    mov r5, _cstr_95
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 12
    mov r1, r5
    jmp r31, strlen
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_96
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 12
    mov r1, r5
    ld r6, r30, 13
    mov r2, r6
    jmp r31, strcmp
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r8, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_97
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 43981
    mov r1, r5
    jmp r31, print_hex
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 90
    st r5, r30, 14
    mov r5, _cstr_98
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 14
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_99
    mov r1, r5
    jmp r31, puts
    mov r6, r1
    mov r5, 0
    mov r1, r5
    jmp main._ret
main._ret:
    ld r31, r30, 15
    add r30, 16
    jmp r31


; ── string literals ──
_cstr_1: dw 58, 32, 0
_cstr_2: dw 79, 75, 0
_cstr_16: dw 61, 61, 61, 32, 116, 101, 115, 116, 95, 97, 108, 108, 32, 61, 61, 61, 0
_cstr_17: dw 51, 43, 52, 0
_cstr_18: dw 49, 48, 45, 51, 0
_cstr_19: dw 54, 42, 55, 0
_cstr_20: dw 50, 48, 47, 52, 0
_cstr_21: dw 49, 55, 37, 53, 0
_cstr_22: dw 53, 38, 51, 0
_cstr_23: dw 53, 124, 51, 0
_cstr_24: dw 53, 94, 51, 0
_cstr_25: dw 126, 48, 0
_cstr_26: dw 49, 60, 60, 52, 0
_cstr_27: dw 51, 50, 62, 62, 50, 0
_cstr_28: dw 51, 61, 61, 51, 0
_cstr_31: dw 51, 33, 61, 52, 0
_cstr_34: dw 50, 60, 53, 0
_cstr_37: dw 53, 62, 50, 0
_cstr_40: dw 38, 38, 0
_cstr_44: dw 124, 124, 0
_cstr_48: dw 33, 0
_cstr_51: dw 43, 61, 0
_cstr_52: dw 45, 61, 0
_cstr_53: dw 42, 61, 0
_cstr_54: dw 47, 61, 0
_cstr_55: dw 38, 61, 0
_cstr_56: dw 124, 61, 0
_cstr_57: dw 94, 61, 0
_cstr_58: dw 43, 43, 121, 0
_cstr_59: dw 121, 43, 43, 0
_cstr_60: dw 121, 0
_cstr_61: dw 45, 45, 121, 0
_cstr_66: dw 105, 102, 58, 84, 0
_cstr_67: dw 105, 102, 58, 70, 0
_cstr_68: dw 119, 104, 105, 108, 101, 58, 0
_cstr_82: dw 102, 111, 114, 58, 0
_cstr_88: dw 53, 33, 0
_cstr_89: dw 102, 105, 98, 55, 0
_cstr_90: dw 115, 117, 109, 0
_cstr_91: dw 112, 0
_cstr_92: dw 113, 0
_cstr_93: dw 104, 101, 108, 108, 111, 0
_cstr_94: dw 104, 101, 108, 108, 111, 0
_cstr_95: dw 108, 101, 110, 0
_cstr_96: dw 99, 109, 112, 0
_cstr_97: dw 104, 101, 120, 0
_cstr_98: dw 99, 104, 114, 0
_cstr_99: dw 61, 61, 61, 32, 100, 111, 110, 101, 32, 61, 61, 61, 0

; ── runtime library ──
%include "C:\Users\1265p\Desktop\powder (1)\c2r316\runtime.asm"
