; Generated by C→R316 compiler
%include "common"

; ── entry point ──
start:
    mov r30, 0x800
    jmp r31, __term_init
    jmp r31, main
    hlt

    ; function newline
newline:
    sub r30, 1
    st r31, r30, 0
    mov r5, 10
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
newline._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function print_label
print_label:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    mov r5, _cstr_1
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
print_label._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function print_ok
print_ok:
    sub r30, 1
    st r31, r30, 0
    mov r5, _cstr_2
    mov r1, r5
    jmp r31, puts
    mov r6, r1
print_ok._ret:
    ld r31, r30, 0
    add r30, 1
    jmp r31

    ; function factorial
factorial:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 1
    sub r0, r5, r6
    jle ._c2r_ct_5
    mov r5, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r5, 1
._c2r_ce_6:
    test r5, r5
    jz ._c2r_else_3
    mov r5, 1
    mov r1, r5
    jmp factorial._ret
._c2r_else_3:
    ld r5, r30, 0
    ld r6, r30, 0
    mov r7, 1
    sub r6, r7
    mov r1, r6
    jmp r31, factorial
    mov r7, r1
    mul r5, r5, r7
    mov r1, r5
    jmp factorial._ret
factorial._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function fib
fib:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 1
    sub r0, r5, r6
    jle ._c2r_ct_9
    mov r5, 0
    jmp ._c2r_ce_10
._c2r_ct_9:
    mov r5, 1
._c2r_ce_10:
    test r5, r5
    jz ._c2r_else_7
    ld r5, r30, 0
    mov r1, r5
    jmp fib._ret
._c2r_else_7:
    ld r5, r30, 0
    mov r6, 1
    sub r5, r6
    mov r1, r5
    jmp r31, fib
    mov r6, r1
    ld r7, r30, 0
    mov r8, 2
    sub r7, r8
    mov r1, r7
    jmp r31, fib
    mov r8, r1
    add r6, r8
    mov r1, r6
    jmp fib._ret
fib._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function array_sum
array_sum:
    sub r30, 4
    st r1, r30, 2
    st r2, r30, 3
    mov r5, 0
    st r5, r30, 1
    mov r5, 0
    st r5, r30, 0
._c2r_fcond_11:
    ld r6, r30, 0
    ld r7, r30, 3
    sub r0, r6, r7
    jl ._c2r_ct_14
    mov r6, 0
    jmp ._c2r_ce_15
._c2r_ct_14:
    mov r6, 1
._c2r_ce_15:
    test r6, r6
    jz ._c2r_fend_13
    ld r5, r30, 1
    ld r6, r30, 2
    ld r7, r30, 0
    add r6, r7
    ld r6, r6
    add r5, r6
    st r5, r30, 1
._c2r_fstep_12:
    mov r6, r30
    ld r7, r6
    mov r8, r7
    add r8, 1
    st r8, r6
    jmp ._c2r_fcond_11
._c2r_fend_13:
    ld r5, r30, 1
    mov r1, r5
    jmp array_sum._ret
array_sum._ret:
    add r30, 4
    jmp r31

    ; function swap
swap:
    sub r30, 3
    st r1, r30, 1
    st r2, r30, 2
    ld r5, r30, 1
    ld r5, r5
    st r5, r30, 0
    ld r5, r30, 2
    ld r5, r5
    ld r6, r30, 1
    st r5, r6
    ld r5, r30, 0
    ld r6, r30, 2
    st r5, r6
swap._ret:
    add r30, 3
    jmp r31

    ; function main
main:
    sub r30, 16
    st r31, r30, 15
    mov r5, _cstr_16
    mov r1, r5
    jmp r31, puts
    mov r6, r1
    mov r5, _cstr_17
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 4
    add r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_18
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 10
    mov r6, 3
    sub r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_19
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 6
    mov r6, 7
    mul r5, r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_20
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 20
    mov r6, 4
    mov r1, r5
    mov r2, r6
    jmp r31, __sdiv
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_21
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 17
    mov r6, 5
    mov r1, r5
    mov r2, r6
    jmp r31, __smod
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_22
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    and r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_23
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    or  r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_24
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 3
    xor r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_25
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 0
    xor r5, 0xFFFF
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_26
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 1
    mov r6, 4
    shl r5, r6
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_27
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 32
    mov r6, 2
    mov r7, r5
    shr r7, 15
    shr r5, r6
    test r7, r7
    jz ._c2r_sar_28
    mov r8, 0xFFFF
    shr r8, r6
    xor r8, 0xFFFF
    or  r5, r8
._c2r_sar_28:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_29
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 3
    sub r0, r5, r6
    jz ._c2r_ct_30
    mov r5, 0
    jmp ._c2r_ce_31
._c2r_ct_30:
    mov r5, 1
._c2r_ce_31:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_32
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 3
    mov r6, 4
    sub r0, r5, r6
    jnz ._c2r_ct_33
    mov r5, 0
    jmp ._c2r_ce_34
._c2r_ct_33:
    mov r5, 1
._c2r_ce_34:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_35
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 2
    mov r6, 5
    sub r0, r5, r6
    jl ._c2r_ct_36
    mov r5, 0
    jmp ._c2r_ce_37
._c2r_ct_36:
    mov r5, 1
._c2r_ce_37:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_38
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r6, 2
    sub r0, r5, r6
    jnle ._c2r_ct_39
    mov r5, 0
    jmp ._c2r_ce_40
._c2r_ct_39:
    mov r5, 1
._c2r_ce_40:
    mov r1, r5
    jmp r31, print_int
    mov r5, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_41
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r6, 1
    mov r5, r6
    test r5, r5
    jz ._c2r_sc_42
    mov r6, 1
    mov r5, r6
._c2r_sc_42:
    test r5, r5
    jnz ._c2r_sct_43
    mov r5, 0
    jmp ._c2r_sce_44
._c2r_sct_43:
    mov r5, 1
._c2r_sce_44:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_45
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r6, 0
    mov r5, r6
    test r5, r5
    jnz ._c2r_sc_46
    mov r6, 1
    mov r5, r6
._c2r_sc_46:
    test r5, r5
    jnz ._c2r_sct_47
    mov r5, 0
    jmp ._c2r_sce_48
._c2r_sct_47:
    mov r5, 1
._c2r_sce_48:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_49
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 0
    test r5, r5
    jz ._c2r_nt_50
    mov r5, 0
    jmp ._c2r_ne_51
._c2r_nt_50:
    mov r5, 1
._c2r_ne_51:
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 10
    st r5, r30, 0
    ld r5, r30, 0
    mov r6, 5
    add r5, r6
    st r5, r30, 0
    mov r5, _cstr_52
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 3
    sub r5, r6
    st r5, r30, 0
    mov r5, _cstr_53
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 2
    mul r5, r5, r6
    st r5, r30, 0
    mov r5, _cstr_54
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 4
    mov r1, r5
    mov r2, r6
    jmp r31, __udiv
    mov r5, r1
    st r5, r30, 0
    mov r5, _cstr_55
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 5
    and r5, r6
    st r5, r30, 0
    mov r5, _cstr_56
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 8
    or r5, r6
    st r5, r30, 0
    mov r5, _cstr_57
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    ld r5, r30, 0
    mov r6, 3
    xor r5, r6
    st r5, r30, 0
    mov r5, _cstr_58
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 5
    st r5, r30, 1
    mov r5, _cstr_59
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    add r6, 1
    st r6, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_60
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_61
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 1
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_62
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    add r5, r30, 1
    ld r6, r5
    sub r6, 1
    st r6, r5
    mov r1, r6
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 7
    st r5, r30, 2
    ld r5, r30, 2
    mov r6, 5
    sub r0, r5, r6
    jnle ._c2r_ct_65
    mov r5, 0
    jmp ._c2r_ce_66
._c2r_ct_65:
    mov r5, 1
._c2r_ce_66:
    test r5, r5
    jz ._c2r_else_63
    mov r5, _cstr_67
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    jmp ._c2r_endif_64
._c2r_else_63:
    mov r5, _cstr_68
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp r31, newline
    mov r5, r1
._c2r_endif_64:
    mov r5, 0
    st r5, r30, 3
    mov r5, _cstr_69
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
._c2r_wcond_70:
    ld r5, r30, 3
    mov r6, 10
    sub r0, r5, r6
    jl ._c2r_ct_73
    mov r5, 0
    jmp ._c2r_ce_74
._c2r_ct_73:
    mov r5, 1
._c2r_ce_74:
    test r5, r5
    jz ._c2r_wend_72
    add r5, r30, 3
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    ld r5, r30, 3
    mov r6, 3
    sub r0, r5, r6
    jz ._c2r_ct_77
    mov r5, 0
    jmp ._c2r_ce_78
._c2r_ct_77:
    mov r5, 1
._c2r_ce_78:
    test r5, r5
    jz ._c2r_else_75
    jmp ._c2r_wcond_70
._c2r_else_75:
    ld r5, r30, 3
    mov r6, 7
    sub r0, r5, r6
    jz ._c2r_ct_81
    mov r5, 0
    jmp ._c2r_ce_82
._c2r_ct_81:
    mov r5, 1
._c2r_ce_82:
    test r5, r5
    jz ._c2r_else_79
    jmp ._c2r_wend_72
._c2r_else_79:
    ld r5, r30, 3
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    mov r5, 32
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_wcond_70
._c2r_wend_72:
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_83
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    mov r5, 0
    st r5, r30, 4
._c2r_fcond_84:
    ld r6, r30, 4
    mov r7, 5
    sub r0, r6, r7
    jl ._c2r_ct_87
    mov r6, 0
    jmp ._c2r_ce_88
._c2r_ct_87:
    mov r6, 1
._c2r_ce_88:
    test r6, r6
    jz ._c2r_fend_86
    ld r5, r30, 4
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    mov r5, 32
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_fstep_85:
    add r7, r30, 4
    ld r8, r7
    mov r9, r8
    add r9, 1
    st r9, r7
    jmp ._c2r_fcond_84
._c2r_fend_86:
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_89
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 5
    mov r1, r5
    jmp r31, factorial
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_90
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 7
    mov r1, r5
    jmp r31, fib
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 10
    ld r6, r30, 5
    mov r7, 0
    add r6, r7
    st r5, r6
    mov r5, 20
    ld r6, r30, 5
    mov r7, 1
    add r6, r7
    st r5, r6
    mov r5, 30
    ld r6, r30, 5
    mov r7, 2
    add r6, r7
    st r5, r6
    mov r5, 40
    ld r6, r30, 5
    mov r7, 3
    add r6, r7
    st r5, r6
    mov r5, 50
    ld r6, r30, 5
    mov r7, 4
    add r6, r7
    st r5, r6
    mov r5, _cstr_91
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 5
    mov r6, 5
    mov r1, r5
    mov r2, r6
    jmp r31, array_sum
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r8, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 11
    st r5, r30, 10
    mov r5, 22
    st r5, r30, 11
    add r5, r30, 10
    add r6, r30, 11
    mov r1, r5
    mov r2, r6
    jmp r31, swap
    mov r7, r1
    mov r5, _cstr_92
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 10
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_93
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 11
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_94
    st r5, r30, 12
    mov r5, _cstr_95
    st r5, r30, 13
    mov r5, _cstr_96
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 12
    mov r1, r5
    jmp r31, strlen
    mov r6, r1
    mov r1, r6
    jmp r31, print_int
    mov r7, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_97
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 12
    ld r6, r30, 13
    mov r1, r5
    mov r2, r6
    jmp r31, strcmp
    mov r7, r1
    mov r1, r7
    jmp r31, print_int
    mov r8, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_98
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    mov r5, 43981
    mov r1, r5
    jmp r31, print_hex
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, 90
    st r5, r30, 14
    mov r5, _cstr_99
    mov r1, r5
    jmp r31, print_label
    mov r6, r1
    ld r5, r30, 14
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp r31, newline
    mov r5, r1
    mov r5, _cstr_100
    mov r1, r5
    jmp r31, puts
    mov r6, r1
    mov r5, 0
    mov r1, r5
    jmp main._ret
main._ret:
    ld r31, r30, 15
    add r30, 16
    jmp r31


; ── string literals ──
_cstr_1: dw 58, 32, 0
_cstr_2: dw 79, 75, 0
_cstr_16: dw 61, 61, 61, 32, 116, 101, 115, 116, 95, 97, 108, 108, 32, 61, 61, 61, 0
_cstr_17: dw 51, 43, 52, 0
_cstr_18: dw 49, 48, 45, 51, 0
_cstr_19: dw 54, 42, 55, 0
_cstr_20: dw 50, 48, 47, 52, 0
_cstr_21: dw 49, 55, 37, 53, 0
_cstr_22: dw 53, 38, 51, 0
_cstr_23: dw 53, 124, 51, 0
_cstr_24: dw 53, 94, 51, 0
_cstr_25: dw 126, 48, 0
_cstr_26: dw 49, 60, 60, 52, 0
_cstr_27: dw 51, 50, 62, 62, 50, 0
_cstr_29: dw 51, 61, 61, 51, 0
_cstr_32: dw 51, 33, 61, 52, 0
_cstr_35: dw 50, 60, 53, 0
_cstr_38: dw 53, 62, 50, 0
_cstr_41: dw 38, 38, 0
_cstr_45: dw 124, 124, 0
_cstr_49: dw 33, 0
_cstr_52: dw 43, 61, 0
_cstr_53: dw 45, 61, 0
_cstr_54: dw 42, 61, 0
_cstr_55: dw 47, 61, 0
_cstr_56: dw 38, 61, 0
_cstr_57: dw 124, 61, 0
_cstr_58: dw 94, 61, 0
_cstr_59: dw 43, 43, 121, 0
_cstr_60: dw 121, 43, 43, 0
_cstr_61: dw 121, 0
_cstr_62: dw 45, 45, 121, 0
_cstr_67: dw 105, 102, 58, 84, 0
_cstr_68: dw 105, 102, 58, 70, 0
_cstr_69: dw 119, 104, 105, 108, 101, 58, 0
_cstr_83: dw 102, 111, 114, 58, 0
_cstr_89: dw 53, 33, 0
_cstr_90: dw 102, 105, 98, 55, 0
_cstr_91: dw 115, 117, 109, 0
_cstr_92: dw 112, 0
_cstr_93: dw 113, 0
_cstr_94: dw 104, 101, 108, 108, 111, 0
_cstr_95: dw 104, 101, 108, 108, 111, 0
_cstr_96: dw 108, 101, 110, 0
_cstr_97: dw 99, 109, 112, 0
_cstr_98: dw 104, 101, 120, 0
_cstr_99: dw 99, 104, 114, 0
_cstr_100: dw 61, 61, 61, 32, 100, 111, 110, 101, 32, 61, 61, 61, 0

; ── runtime library (compiled from runtime.c) ──
    ; function _print_digits
_print_digits:
    sub r30, 4
    st r31, r30, 3
    st r1, r30, 2
    ld r5, r30, 2
    mov r6, 10
    mov r1, r5
    mov r2, r6
    jmp r31, __udiv
    mov r7, r1
    st r7, r30, 0
    ld r5, r30, 2
    mov r6, 10
    mov r1, r5
    mov r2, r6
    jmp r31, __umod
    mov r7, r1
    st r7, r30, 1
    ld r5, r30, 0
    test r5, r5
    jz ._c2r_else_1
    ld r5, r30, 0
    mov r1, r5
    jmp r31, _print_digits
    mov r6, r1
._c2r_else_1:
    mov r5, 48
    ld r6, r30, 1
    add r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
_print_digits._ret:
    ld r31, r30, 3
    add r30, 4
    jmp r31

    ; function print_uint
print_uint:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 0
    sub r0, r5, r6
    jz ._c2r_ct_5
    mov r5, 0
    jmp ._c2r_ce_6
._c2r_ct_5:
    mov r5, 1
._c2r_ce_6:
    test r5, r5
    jz ._c2r_else_3
    mov r5, 48
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp print_uint._ret
._c2r_else_3:
    ld r5, r30, 0
    mov r1, r5
    jmp r31, _print_digits
    mov r6, r1
print_uint._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function print_int
print_int:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r6, 0
    sub r0, r5, r6
    jl ._c2r_ct_9
    mov r5, 0
    jmp ._c2r_ce_10
._c2r_ct_9:
    mov r5, 1
._c2r_ce_10:
    test r5, r5
    jz ._c2r_else_7
    mov r5, 45
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    ld r5, r30, 0
    sub r5, r0, r5
    st r5, r30, 0
._c2r_else_7:
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_uint
    mov r6, r1
print_int._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function print_hex
print_hex:
    sub r30, 4
    st r31, r30, 3
    st r1, r30, 2
    mov r5, 0
    st r5, r30, 0
._c2r_fcond_11:
    ld r6, r30, 0
    mov r7, 4
    sub r0, r6, r7
    jl ._c2r_ct_14
    mov r6, 0
    jmp ._c2r_ce_15
._c2r_ct_14:
    mov r6, 1
._c2r_ce_15:
    test r6, r6
    jz ._c2r_fend_13
    ld r5, r30, 2
    mov r6, 12
    shr r5, r6
    mov r6, 15
    and r5, r6
    st r5, r30, 1
    ld r5, r30, 1
    mov r6, 10
    sub r0, r5, r6
    jnl ._c2r_ct_18
    mov r5, 0
    jmp ._c2r_ce_19
._c2r_ct_18:
    mov r5, 1
._c2r_ce_19:
    test r5, r5
    jz ._c2r_else_16
    mov r5, 65
    ld r6, r30, 1
    add r5, r6
    mov r6, 10
    sub r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_endif_17
._c2r_else_16:
    mov r5, 48
    ld r6, r30, 1
    add r5, r6
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_endif_17:
    ld r5, r30, 2
    mov r6, 4
    shl r5, r6
    st r5, r30, 2
._c2r_fstep_12:
    mov r6, r30
    ld r7, r6
    mov r8, r7
    add r8, 1
    st r8, r6
    jmp ._c2r_fcond_11
._c2r_fend_13:
print_hex._ret:
    ld r31, r30, 3
    add r30, 4
    jmp r31

    ; function print_str
print_str:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
._c2r_wcond_20:
    ld r5, r30, 0
    ld r5, r5
    test r5, r5
    jz ._c2r_wend_22
    ld r5, r30, 0
    ld r5, r5
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_20
._c2r_wend_22:
print_str._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function puts
puts:
    sub r30, 2
    st r31, r30, 1
    st r1, r30, 0
    ld r5, r30, 0
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    mov r5, 10
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
puts._ret:
    ld r31, r30, 1
    add r30, 2
    jmp r31

    ; function strlen
strlen:
    sub r30, 2
    st r1, r30, 1
    mov r5, 0
    st r5, r30, 0
._c2r_wcond_23:
    ld r5, r30, 1
    ld r5, r5
    test r5, r5
    jz ._c2r_wend_25
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_23
._c2r_wend_25:
    ld r5, r30, 0
    mov r1, r5
    jmp strlen._ret
strlen._ret:
    add r30, 2
    jmp r31

    ; function strcmp
strcmp:
    sub r30, 2
    st r1, r30, 0
    st r2, r30, 1
._c2r_wcond_26:
    ld r6, r30, 0
    ld r6, r6
    mov r5, r6
    test r5, r5
    jz ._c2r_sc_29
    ld r6, r30, 0
    ld r6, r6
    ld r7, r30, 1
    ld r7, r7
    sub r0, r6, r7
    jz ._c2r_ct_30
    mov r6, 0
    jmp ._c2r_ce_31
._c2r_ct_30:
    mov r6, 1
._c2r_ce_31:
    mov r5, r6
._c2r_sc_29:
    test r5, r5
    jnz ._c2r_sct_32
    mov r5, 0
    jmp ._c2r_sce_33
._c2r_sct_32:
    mov r5, 1
._c2r_sce_33:
    test r5, r5
    jz ._c2r_wend_28
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    jmp ._c2r_wcond_26
._c2r_wend_28:
    ld r5, r30, 0
    ld r5, r5
    ld r6, r30, 1
    ld r6, r6
    sub r5, r6
    mov r1, r5
    jmp strcmp._ret
strcmp._ret:
    add r30, 2
    jmp r31

    ; function memset
memset:
    sub r30, 3
    st r1, r30, 0
    st r2, r30, 1
    st r3, r30, 2
._c2r_wcond_34:
    ld r5, r30, 2
    mov r6, 0
    sub r0, r5, r6
    jnle ._c2r_ct_37
    mov r5, 0
    jmp ._c2r_ce_38
._c2r_ct_37:
    mov r5, 1
._c2r_ce_38:
    test r5, r5
    jz ._c2r_wend_36
    ld r5, r30, 1
    ld r6, r30, 0
    st r5, r6
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 2
    ld r6, r5
    mov r7, r6
    sub r7, 1
    st r7, r5
    jmp ._c2r_wcond_34
._c2r_wend_36:
memset._ret:
    add r30, 3
    jmp r31

    ; function memcpy
memcpy:
    sub r30, 3
    st r1, r30, 0
    st r2, r30, 1
    st r3, r30, 2
._c2r_wcond_39:
    ld r5, r30, 2
    mov r6, 0
    sub r0, r5, r6
    jnle ._c2r_ct_42
    mov r5, 0
    jmp ._c2r_ce_43
._c2r_ct_42:
    mov r5, 1
._c2r_ce_43:
    test r5, r5
    jz ._c2r_wend_41
    ld r5, r30, 1
    ld r5, r5
    ld r6, r30, 0
    st r5, r6
    mov r5, r30
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 1
    ld r6, r5
    mov r7, r6
    add r7, 1
    st r7, r5
    add r5, r30, 2
    ld r6, r5
    mov r7, r6
    sub r7, 1
    st r7, r5
    jmp ._c2r_wcond_39
._c2r_wend_41:
memcpy._ret:
    add r30, 3
    jmp r31

    ; function printf
printf:
    sub r30, 6
    st r31, r30, 5
    st r1, r30, 4
    mov r5, r30
    add r6, r30, 6
    st r6, r5
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
._c2r_wcond_44:
    ld r5, r30, 1
    test r5, r5
    jz ._c2r_wend_46
    ld r5, r30, 1
    mov r6, 37
    sub r0, r5, r6
    jz ._c2r_ct_49
    mov r5, 0
    jmp ._c2r_ce_50
._c2r_ct_49:
    mov r5, 1
._c2r_ce_50:
    test r5, r5
    jz ._c2r_else_47
    ld r5, r30, 4
    mov r6, 1
    add r5, r6
    st r5, r30, 4
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
    ld r5, r30, 1
    mov r6, 100
    sub r0, r5, r6
    jz ._c2r_ct_53
    mov r5, 0
    jmp ._c2r_ce_54
._c2r_ct_53:
    mov r5, 1
._c2r_ce_54:
    test r5, r5
    jz ._c2r_else_51
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_int
    mov r6, r1
    jmp ._c2r_endif_52
._c2r_else_51:
    ld r5, r30, 1
    mov r6, 117
    sub r0, r5, r6
    jz ._c2r_ct_57
    mov r5, 0
    jmp ._c2r_ce_58
._c2r_ct_57:
    mov r5, 1
._c2r_ce_58:
    test r5, r5
    jz ._c2r_else_55
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_uint
    mov r6, r1
    jmp ._c2r_endif_56
._c2r_else_55:
    ld r5, r30, 1
    mov r6, 120
    sub r0, r5, r6
    jz ._c2r_ct_61
    mov r5, 0
    jmp ._c2r_ce_62
._c2r_ct_61:
    mov r5, 1
._c2r_ce_62:
    test r5, r5
    jz ._c2r_else_59
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, print_hex
    mov r6, r1
    jmp ._c2r_endif_60
._c2r_else_59:
    ld r5, r30, 1
    mov r6, 115
    sub r0, r5, r6
    jz ._c2r_ct_65
    mov r5, 0
    jmp ._c2r_ce_66
._c2r_ct_65:
    mov r5, 1
._c2r_ce_66:
    test r5, r5
    jz ._c2r_else_63
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 3
    ld r5, r30, 3
    mov r1, r5
    jmp r31, print_str
    mov r6, r1
    jmp ._c2r_endif_64
._c2r_else_63:
    ld r5, r30, 1
    mov r6, 99
    sub r0, r5, r6
    jz ._c2r_ct_69
    mov r5, 0
    jmp ._c2r_ce_70
._c2r_ct_69:
    mov r5, 1
._c2r_ce_70:
    test r5, r5
    jz ._c2r_else_67
    mov r5, r30
    ld r6, r5
    ld r7, r6
    add r6, 1
    st r6, r5
    st r7, r30, 2
    ld r5, r30, 2
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
    jmp ._c2r_endif_68
._c2r_else_67:
    ld r5, r30, 1
    mov r6, 37
    sub r0, r5, r6
    jz ._c2r_ct_73
    mov r5, 0
    jmp ._c2r_ce_74
._c2r_ct_73:
    mov r5, 1
._c2r_ce_74:
    test r5, r5
    jz ._c2r_else_71
    mov r5, 37
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_else_71:
._c2r_endif_68:
._c2r_endif_64:
._c2r_endif_60:
._c2r_endif_56:
._c2r_endif_52:
    jmp ._c2r_endif_48
._c2r_else_47:
    ld r5, r30, 1
    mov r1, r5
    jmp r31, putchar
    mov r6, r1
._c2r_endif_48:
    ld r5, r30, 4
    mov r6, 1
    add r5, r6
    st r5, r30, 4
    ld r5, r30, 4
    ld r5, r5
    st r5, r30, 1
    jmp ._c2r_wcond_44
._c2r_wend_46:
printf._ret:
    ld r31, r30, 5
    add r30, 6
    jmp r31


; ── runtime core (asm) ──
%include "runtime_core.asm"
