"""
C to R316 Compiler - Code Generator
AST -> TPTASM R316 assembly

ABI:
  r1..r4  : arguments / return value (r1=lo, r2=hi for long)
  r5..r13 : caller-saved temporaries
  r14..r29: callee-saved
  r30 (sp): stack pointer (grows downward)
  r31 (lr): link register

Stack frame layout (non-leaf):
  [sp+0 .. sp+local_size-1]        : local variables
  [sp+local_size .. sp+callee_base-1] : param 1-4 spill slots
  [sp+callee_base .. sp+lr_slot-1]  : callee-saved regs (r14-r17, if used)
  [sp+lr_slot]                      : saved lr

Register allocation strategy:
  Linear allocator over r5..r13 (caller-saved) then r14..r17 (callee-saved).
  Callee-saved regs are saved/restored per-function via two-pass body generation.
  Caller saves r5..r13 around each function call when outer regs are live.
"""

from ast_nodes import *
import re as _re
import sys


# ABI constants
SP = 'r30'
LR = 'r31'
ARG_REGS        = ['r1', 'r2', 'r3', 'r4']
RET_REG         = 'r1'
RET_REG_H       = 'r2'
CALLER_TMP_REGS = ['r5', 'r6', 'r7', 'r8', 'r9', 'r10', 'r11', 'r12', 'r13']
CALLEE_SAVED_REGS = ['r14', 'r15', 'r16', 'r17']
TMP_REGS        = CALLER_TMP_REGS + CALLEE_SAVED_REGS   # 13 total


class CodegenError(Exception):
    pass


class RegAlloc:
    """Linear temporary register allocator with callee-saved register tracking."""
    def __init__(self):
        self._used = 0
        self._callee_used: set = set()

    def alloc(self) -> str:
        if self._used < len(TMP_REGS):
            r = TMP_REGS[self._used]
            self._used += 1
            if r in CALLEE_SAVED_REGS:
                self._callee_used.add(r)
            return r
        raise CodegenError(
            f"Ran out of temporary registers ({len(TMP_REGS)} total). "
            "Simplify the expression or split into sub-expressions."
        )

    def free(self):
        if self._used > 0:
            self._used -= 1

    def checkpoint(self) -> int:
        return self._used

    def restore(self, cp: int):
        self._used = cp

    def reset_callee_tracking(self):
        self._callee_used = set()

    def callee_saved_used(self) -> list:
        """Return sorted list of callee-saved registers actually used."""
        return sorted(self._callee_used, key=lambda r: int(r[1:]))


def _ptr_step(ctype) -> int:
    """Return the address increment for one ++ or -- step on a value of ctype."""
    if isinstance(ctype, (CPointer, CArray)):
        base = getattr(ctype, 'base', None)
        return base.size() if base and base.size() > 0 else 1
    return 1


class Codegen:
    def __init__(self, library_mode: bool = False):
        self._library_mode   = library_mode
        self.out: list[str]  = []
        self._label_cnt      = 0
        self._string_data: list[tuple[str, list[int]]] = []
        self._global_vars: list[VarDecl] = []
        self._loop_break_stack: list[str]    = []
        self._loop_cont_stack:  list[str]    = []
        self._regs = RegAlloc()
        self._local_vars: dict[str, tuple[int, CType]] = {}  # name -> (sp_offset, type)
        self._param_regs: dict[str, str] = {}   # name -> register
        self._local_size = 0
        self._current_ret_type: CType = CVoid()

    # ── Output helpers ────────────────────────────────────────────────────────

    def _emit(self, line: str):
        self.out.append(line)

    def _label(self, name: str):
        self._emit(f'{name}:')

    def _new_label(self, prefix='L') -> str:
        self._label_cnt += 1
        return f'._c2r_{prefix}_{self._label_cnt}'

    def _comment(self, txt: str):
        self._emit(f'    ; {txt}')

    # ── Top-level ─────────────────────────────────────────────────────────────

    def generate(self, prog: Program) -> str:
        # collect global variables and functions
        funcs = []
        for decl in prog.decls:
            if isinstance(decl, FuncDecl):
                funcs.append(decl)
            elif isinstance(decl, VarDecl):
                self._global_vars.append(decl)

        if not self._library_mode:
            self._emit('; Generated by C->R316 compiler')
            self._emit('%include "common"')
            self._emit('')
            # runtime entry point
            self._emit('; -- entry point --')
            self._emit('start:')
            self._emit(f'    mov {SP}, 0x800')
            self._emit(f'    jmp {LR}, __term_init')
            self._emit(f'    jmp {LR}, main')
            self._emit(f'    hlt')
            self._emit('')

        # generate function code
        for func in funcs:
            if func.body is not None:
                self._gen_func(func)

        # global variable data
        if self._global_vars:
            self._emit('; -- global variables --')
            for v in self._global_vars:
                self._gen_global_var(v)

        # string literals
        if self._string_data:
            self._emit('')
            self._emit('; -- string literals --')
            for label, chars in self._string_data:
                data = ', '.join(str(c) for c in chars) + ', 0'
                self._emit(f'{label}: dw {data}')

        return '\n'.join(self.out)

    # ── Global variables ──────────────────────────────────────────────────────

    def _gen_global_var(self, v: VarDecl):
        if isinstance(v.ctype, CArray):
            size = v.ctype.size() or 0
            if isinstance(v.init, InitList):
                vals = []
                for item in v.init.items:
                    if isinstance(item, IntLit):
                        vals.append(item.value & 0xFFFF)
                    elif isinstance(item, CharLit):
                        vals.append(item.value & 0xFF)
                    else:
                        vals.append(0)
                # pad with zeros if fewer initializers than array size
                if size == 0:
                    size = len(vals)
                while len(vals) < size:
                    vals.append(0)
                self._emit(f'{v.name}: dw {", ".join(str(x) for x in vals)}')
            else:
                self._emit(f'{v.name}: dw {", ".join(["0"] * max(size, 1))}')
        else:
            val = 0
            if isinstance(v.init, IntLit):
                val = v.init.value & 0xFFFF
            elif isinstance(v.init, CharLit):
                val = v.init.value & 0xFF
            self._emit(f'{v.name}: dw {val}')

    # ── Functions ─────────────────────────────────────────────────────────────

    def _gen_func(self, func: FuncDecl):
        self._comment(f'function {func.name}')
        self._label(func.name)

        # reset local state
        self._local_vars  = {}
        self._param_regs  = {}
        self._local_size  = getattr(func, '_local_size', 0)
        self._current_ret_type = func.ret_type

        is_leaf = self._is_leaf(func.body)

        # Compute param 1-4 spill slots (unchanged by callee reg count)
        param_offset = self._local_size
        for i, param in enumerate(func.params):
            if i >= 4:
                break
            sz = max(param.ctype.size(), 1)
            self._local_vars[param.name] = (param_offset, param.ctype)
            param_offset += sz
        param_spill_size = param_offset - self._local_size

        # callee_base = first slot after local vars and param 1-4 spill
        callee_base = self._local_size + param_spill_size
        n_stack_params = max(0, len(func.params) - 4)

        # ── Pass 1: generate body into a temp buffer ──────────────────────────
        # We need to know which callee-saved regs are actually used before we
        # can compute the final frame layout and emit the prologue.
        saved_out = self.out
        self.out = []
        self._regs.restore(0)
        self._regs.reset_callee_tracking()

        # Provisional frame_size (no callee regs yet) for params 5+ offset calc
        prov_lr_slot = callee_base          # provisional LR position
        prov_frame   = callee_base + (1 if not is_leaf else 0)
        self._frame_size = prov_frame

        for i, param in enumerate(func.params):
            if i < 4:
                continue
            self._local_vars[param.name] = (prov_frame + (i - 4), param.ctype)
        self._va_offset = prov_frame + n_stack_params

        # collect local variable offsets (offsets 0..local_size-1, unaffected)
        offset = 0
        for stmt in func.body.stmts:
            offset = self._collect_locals(stmt, offset)

        ret_label = f'{func.name}._ret'
        self._ret_label = ret_label

        self._gen_block(func.body)
        body_lines = self.out
        self.out = saved_out

        # ── Determine actual callee-saved registers used ───────────────────────
        callee_used = self._regs.callee_saved_used()
        n_callee    = len(callee_used)

        # ── Compute final frame layout ─────────────────────────────────────────
        # [0..local_size-1]              local vars
        # [callee_base..callee_base+n_callee-1] callee-saved regs (if any)
        # [lr_slot]                      saved LR (non-leaf only)
        # Above frame: params 5+ (pushed by caller, offset = frame_size + k)
        lr_slot    = callee_base + n_callee
        frame_size = lr_slot + (1 if not is_leaf else 0)
        self._frame_size = frame_size

        # ── Patch params 5+ and va_offset in body if callee regs were added ───
        if n_callee > 0:
            final_frame = frame_size
            # Replace all r30-relative offsets >= prov_frame (params 5+, va)
            # with the same offset + n_callee.  Local/param-spill offsets are
            # < callee_base < prov_frame so they are not affected.
            _sp_pat = _re.compile(r'\b' + _re.escape(SP) + r', (\d+)\b')
            def _fix_offset(m):
                off = int(m.group(1))
                return f'{SP}, {off + n_callee}' if off >= prov_frame else m.group(0)
            body_lines = [_sp_pat.sub(_fix_offset, ln) for ln in body_lines]

        # Update params 5+ and va_offset to final values
        for i, param in enumerate(func.params):
            if i < 4:
                continue
            self._local_vars[param.name] = (frame_size + (i - 4), param.ctype)
        self._va_offset = frame_size + n_stack_params

        # ── Emit prologue ──────────────────────────────────────────────────────
        if frame_size > 0:
            self._emit(f'    sub {SP}, {frame_size}')
        if not is_leaf:
            self._emit(f'    st {LR}, {SP}, {lr_slot}')
        for i, reg in enumerate(callee_used):
            self._emit(f'    st {reg}, {SP}, {callee_base + i}')
        for i, param in enumerate(func.params):
            if i >= len(ARG_REGS):
                break
            slot, _ = self._local_vars[param.name]
            self._emit(f'    st {ARG_REGS[i]}, {SP}, {slot}')

        # ── Emit body ──────────────────────────────────────────────────────────
        self.out.extend(body_lines)

        # ── Emit epilogue ──────────────────────────────────────────────────────
        self._label(ret_label)
        for i in range(n_callee - 1, -1, -1):
            self._emit(f'    ld {callee_used[i]}, {SP}, {callee_base + i}')
        if not is_leaf:
            self._emit(f'    ld {LR}, {SP}, {lr_slot}')
        if frame_size > 0:
            self._emit(f'    add {SP}, {frame_size}')
        self._emit(f'    jmp {LR}')
        self._emit('')

    def _collect_locals(self, stmt: Stmt, offset: int) -> int:
        if isinstance(stmt, DeclStmt):
            d = stmt.decl
            size = max(d.ctype.size(), 1)
            self._local_vars[d.name] = (offset, d.ctype)
            return offset + size
        if isinstance(stmt, Block):
            for s in stmt.stmts:
                offset = self._collect_locals(s, offset)
        if isinstance(stmt, IfStmt):
            offset = self._collect_locals(stmt.then, offset)
            if stmt.else_:
                offset = self._collect_locals(stmt.else_, offset)
        if isinstance(stmt, (WhileStmt, DoWhileStmt)):
            offset = self._collect_locals(stmt.body, offset)
        if isinstance(stmt, ForStmt):
            if stmt.init:
                offset = self._collect_locals(stmt.init, offset)
            offset = self._collect_locals(stmt.body, offset)
        if isinstance(stmt, SwitchStmt):
            for case in stmt.cases:
                for s in case.stmts:
                    offset = self._collect_locals(s, offset)
        if isinstance(stmt, LabelStmt):
            offset = self._collect_locals(stmt.stmt, offset)
        return offset

    def _is_leaf(self, block: Optional[Block]) -> bool:
        """A function is a leaf if it makes no calls"""
        if block is None:
            return True
        return not self._has_call(block)

    def _has_call(self, node) -> bool:
        if isinstance(node, Call):
            return True
        if isinstance(node, (Block, ForStmt, WhileStmt)):
            stmts = getattr(node, 'stmts', [])
            if not stmts:
                stmts = []
                for attr in ('init', 'cond', 'step', 'body'):
                    v = getattr(node, attr, None)
                    if v: stmts.append(v)
            return any(self._has_call(s) for s in stmts)
        for attr in vars(node).values() if hasattr(node, '__dict__') else []:
            if isinstance(attr, Node) and self._has_call(attr):
                return True
            if isinstance(attr, list):
                for item in attr:
                    if isinstance(item, Node) and self._has_call(item):
                        return True
        return False

    # ── Statement code generation ─────────────────────────────────────────────

    def _gen_block(self, block: Block):
        for stmt in block.stmts:
            self._gen_stmt(stmt)

    def _gen_stmt(self, stmt: Stmt):
        self._regs.restore(0)

        if isinstance(stmt, Block):
            self._gen_block(stmt)

        elif isinstance(stmt, DeclStmt):
            d = stmt.decl
            if d.init is not None:
                off, ctype = self._local_vars[d.name]
                if isinstance(d.init, InitList):
                    # local array init: store each element into its stack slot
                    for i, item in enumerate(d.init.items):
                        r = self._gen_expr(item)
                        self._emit(f'    st {r}, {SP}, {off + i}')
                else:
                    r = self._gen_expr(d.init)
                    self._emit(f'    st {r}, {SP}, {off}')

        elif isinstance(stmt, ExprStmt):
            self._gen_expr(stmt.expr)

        elif isinstance(stmt, IfStmt):
            self._gen_if(stmt)

        elif isinstance(stmt, WhileStmt):
            self._gen_while(stmt)

        elif isinstance(stmt, ForStmt):
            self._gen_for(stmt)

        elif isinstance(stmt, ReturnStmt):
            if stmt.expr is not None:
                r = self._gen_expr(stmt.expr)
                if r != RET_REG:
                    self._emit(f'    mov {RET_REG}, {r}')
            self._emit(f'    jmp {self._ret_label}')

        elif isinstance(stmt, BreakStmt):
            if not self._loop_break_stack:
                raise CodegenError("break outside loop")
            self._emit(f'    jmp {self._loop_break_stack[-1]}')

        elif isinstance(stmt, ContinueStmt):
            if not self._loop_cont_stack:
                raise CodegenError("continue outside loop")
            self._emit(f'    jmp {self._loop_cont_stack[-1]}')

        elif isinstance(stmt, DoWhileStmt):
            self._gen_do_while(stmt)

        elif isinstance(stmt, SwitchStmt):
            self._gen_switch(stmt)

        elif isinstance(stmt, GotoStmt):
            self._emit(f'    jmp ._lbl_{stmt.label}')

        elif isinstance(stmt, LabelStmt):
            self._label(f'._lbl_{stmt.label}')
            self._gen_stmt(stmt.stmt)

    def _gen_if(self, stmt: IfStmt):
        else_lbl = self._new_label('else')
        end_lbl  = self._new_label('endif')

        cond_r = self._gen_expr(stmt.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._emit(f'    jz {else_lbl}')

        self._gen_stmt(stmt.then)
        if stmt.else_:
            self._emit(f'    jmp {end_lbl}')
        self._label(else_lbl)
        if stmt.else_:
            self._gen_stmt(stmt.else_)
            self._label(end_lbl)

    def _gen_while(self, stmt: WhileStmt):
        cond_lbl = self._new_label('wcond')
        body_lbl = self._new_label('wbody')
        end_lbl  = self._new_label('wend')

        self._loop_break_stack.append(end_lbl)
        self._loop_cont_stack.append(cond_lbl)

        self._label(cond_lbl)
        cond_r = self._gen_expr(stmt.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._emit(f'    jz {end_lbl}')

        self._gen_stmt(stmt.body)
        self._emit(f'    jmp {cond_lbl}')
        self._label(end_lbl)

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _gen_for(self, stmt: ForStmt):
        cond_lbl = self._new_label('fcond')
        step_lbl = self._new_label('fstep')
        end_lbl  = self._new_label('fend')

        if stmt.init:
            self._gen_stmt(stmt.init)

        self._loop_break_stack.append(end_lbl)
        self._loop_cont_stack.append(step_lbl)

        self._label(cond_lbl)
        if stmt.cond:
            cond_r = self._gen_expr(stmt.cond)
            self._emit(f'    test {cond_r}, {cond_r}')
            self._emit(f'    jz {end_lbl}')

        self._gen_stmt(stmt.body)

        self._label(step_lbl)
        if stmt.step:
            self._gen_expr(stmt.step)

        self._emit(f'    jmp {cond_lbl}')
        self._label(end_lbl)

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _gen_do_while(self, stmt: DoWhileStmt):
        body_lbl = self._new_label('dobody')
        end_lbl  = self._new_label('doend')

        self._loop_break_stack.append(end_lbl)
        self._loop_cont_stack.append(body_lbl)

        self._label(body_lbl)
        self._gen_stmt(stmt.body)

        cond_r = self._gen_expr(stmt.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._emit(f'    jnz {body_lbl}')
        self._label(end_lbl)

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _gen_switch(self, stmt: SwitchStmt):
        end_lbl = self._new_label('swend')
        self._loop_break_stack.append(end_lbl)

        expr_r = self._gen_expr(stmt.expr)

        # generate case labels
        case_labels = []
        for case in stmt.cases:
            lbl = self._new_label('swcase') if case.value is not None else self._new_label('swdefault')
            case_labels.append(lbl)

        default_lbl = end_lbl
        for i, case in enumerate(stmt.cases):
            if case.value is None:
                default_lbl = case_labels[i]
                break

        # dispatch: compare expr_r against each case value
        for i, case in enumerate(stmt.cases):
            if case.value is not None:
                cmp_r = self._regs.alloc()
                self._emit(f'    mov {cmp_r}, {case.value & 0xFFFF}')
                self._emit(f'    sub r0, {expr_r}, {cmp_r}')
                self._regs.free()
                self._emit(f'    jz {case_labels[i]}')
        self._emit(f'    jmp {default_lbl}')

        # emit case bodies (fall-through supported)
        for i, case in enumerate(stmt.cases):
            self._label(case_labels[i])
            for s in case.stmts:
                self._gen_stmt(s)

        self._label(end_lbl)
        self._loop_break_stack.pop()

    # ── Expression code generation -> returns result register ─────────────────

    def _gen_expr(self, expr: Expr) -> str:
        """Evaluate an expression and return the register holding the result"""

        if isinstance(expr, IntLit):
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {expr.value & 0xFFFF}')
            return r

        if isinstance(expr, CharLit):
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {expr.value & 0xFF}')
            return r

        if isinstance(expr, StringLit):
            self._label_cnt += 1
            lbl = f'_cstr_{self._label_cnt}'
            expr.label = lbl
            self._string_data.append((lbl, expr.chars))
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {lbl}')
            return r

        if isinstance(expr, Ident):
            return self._gen_load_ident(expr)

        if isinstance(expr, BinOp):
            return self._gen_binop(expr)

        if isinstance(expr, UnaryOp):
            return self._gen_unary(expr)

        if isinstance(expr, Assign):
            return self._gen_assign(expr)

        if isinstance(expr, Call):
            return self._gen_call(expr)

        if isinstance(expr, Index):
            return self._gen_index(expr)

        if isinstance(expr, Cast):
            r = self._gen_expr(expr.expr)
            # simple type cast: mask if needed
            if isinstance(expr.to_type, CChar):
                self._emit(f'    and {r}, 0xFF')
            return r

        if isinstance(expr, SizeOf):
            r = self._regs.alloc()
            if isinstance(expr.target, CType):
                self._emit(f'    mov {r}, {expr.target.size()}')
            else:
                sz = expr.target.ctype.size() if expr.target.ctype else 1
                self._emit(f'    mov {r}, {sz}')
            return r

        if isinstance(expr, Ternary):
            return self._gen_ternary(expr)

        raise CodegenError(f"Unhandled expression: {type(expr)}")

    def _gen_load_ident(self, expr: Ident) -> str:
        name = expr.name
        # parameter register alias
        if name in self._param_regs:
            return self._param_regs[name]
        # local variable
        if name in self._local_vars:
            off, ctype = self._local_vars[name]
            r = self._regs.alloc()
            self._emit(f'    ld {r}, {SP}, {off}')
            return r
        # global variable or function
        r = self._regs.alloc()
        if isinstance(expr.ctype, CFunction):
            self._emit(f'    mov {r}, {name}')
        else:
            self._emit(f'    ld {r}, {name}')
        return r

    def _gen_addr(self, expr: Expr) -> str:
        """Load the address of an lvalue into a register and return it"""
        if isinstance(expr, Ident):
            name = expr.name
            if name in self._local_vars:
                off, _ = self._local_vars[name]
                r = self._regs.alloc()
                self._emit(f'    add {r}, {SP}, {off}' if off else f'    mov {r}, {SP}')
                return r
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {name}')
            return r

        if isinstance(expr, Index):
            arr_r  = self._gen_expr(expr.array)
            idx_r  = self._gen_expr(expr.index)
            elem_sz = expr.ctype.size() if expr.ctype else 1
            if elem_sz > 1:
                self._emit(f'    mul {idx_r}, {idx_r}, {elem_sz}')
            self._emit(f'    add {arr_r}, {idx_r}')
            self._regs.free()  # free idx_r
            return arr_r

        if isinstance(expr, UnaryOp) and expr.op == '*':
            return self._gen_expr(expr.operand)

        raise CodegenError(f"Cannot take address of {type(expr)}")

    def _gen_store(self, val_r: str, target: Expr):
        """Store val_r into the target lvalue"""
        if isinstance(target, Ident):
            name = target.name
            if name in self._local_vars:
                off, _ = self._local_vars[name]
                self._emit(f'    st {val_r}, {SP}, {off}')
                return
            self._emit(f'    st {val_r}, {name}')
            return
        if isinstance(target, Index):
            addr_r = self._gen_addr(target)
            self._emit(f'    st {val_r}, {addr_r}')
            self._regs.free()
            return
        if isinstance(target, UnaryOp) and target.op == '*':
            ptr_r = self._gen_expr(target.operand)
            self._emit(f'    st {val_r}, {ptr_r}')
            self._regs.free()
            return
        raise CodegenError(f"Cannot store into {type(target)}")

    @staticmethod
    def _is_unsigned(*ctypes: CType) -> bool:
        """Returns True if any operand type is unsigned or a pointer"""
        for t in ctypes:
            if isinstance(t, (CPointer, CArray)):
                return True
            if isinstance(t, (CInt, CChar)) and t.unsigned:
                return True
        return False

    def _gen_ternary(self, expr: Ternary) -> str:
        else_lbl = self._new_label('telse')
        end_lbl  = self._new_label('tend')
        cond_r   = self._gen_expr(expr.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._regs.free()
        self._emit(f'    jz {else_lbl}')

        # Record baseline before then-branch so both branches land in same reg.
        cp    = self._regs.checkpoint()
        dst   = TMP_REGS[cp]            # result register is always slot cp
        then_r = self._gen_expr(expr.then)
        if then_r != dst:
            self._emit(f'    mov {dst}, {then_r}')
        self._regs.restore(cp + 1)      # exactly one result reg live
        self._emit(f'    jmp {end_lbl}')

        self._label(else_lbl)
        self._regs.restore(cp)          # reset to baseline for else-branch
        else_r = self._gen_expr(expr.else_)
        if else_r != dst:
            self._emit(f'    mov {dst}, {else_r}')
        self._regs.restore(cp + 1)      # exactly one result reg live

        self._label(end_lbl)
        return dst

    def _gen_binop(self, expr: BinOp) -> str:
        op = expr.op

        # short-circuit evaluation
        if op == '&&':
            return self._gen_short_circuit(expr, False)
        if op == '||':
            return self._gen_short_circuit(expr, True)

        left_r  = self._gen_expr(expr.left)
        right_r = self._gen_expr(expr.right)
        dst     = left_r   # result overwrites left

        if op == '+':
            self._emit(f'    add {dst}, {right_r}')
        elif op == '-':
            self._emit(f'    sub {dst}, {right_r}')
        elif op == '*':
            self._emit(f'    mul {dst}, {dst}, {right_r}')
        elif op == '/':
            div_fn = '__udiv' if self._is_unsigned(expr.left.ctype, expr.right.ctype) else '__sdiv'
            self._emit(f'    mov r1, {dst}')
            self._emit(f'    mov r2, {right_r}')
            self._emit(f'    jmp r31, {div_fn}')
            # Reuse left_r (= dst) for the result; __udiv/__sdiv return quotient
            # in r1 and do NOT touch r5-r17, so dst is still safe to write into.
            self._emit(f'    mov {dst}, r1')
        elif op == '%':
            mod_fn = '__umod' if self._is_unsigned(expr.left.ctype, expr.right.ctype) else '__smod'
            self._emit(f'    mov r1, {dst}')
            self._emit(f'    mov r2, {right_r}')
            self._emit(f'    jmp r31, {mod_fn}')
            # __umod/__smod return remainder in r1
            self._emit(f'    mov {dst}, r1')
        elif op == '&':
            self._emit(f'    and {dst}, {right_r}')
        elif op == '|':
            self._emit(f'    or  {dst}, {right_r}')
        elif op == '^':
            self._emit(f'    xor {dst}, {right_r}')
        elif op == '<<':
            self._emit(f'    shl {dst}, {right_r}')
        elif op == '>>':
            if self._is_unsigned(expr.left.ctype):
                # unsigned: logical shift (zero fill)
                self._emit(f'    shr {dst}, {right_r}')
            else:
                # signed: arithmetic shift (sign fill)
                # R316 shr is always logical, so sign-extend inline
                sign_r = self._regs.alloc()   # save original sign bit
                mask_r = self._regs.alloc()   # fill mask
                self._emit(f'    mov {sign_r}, {dst}')
                self._emit(f'    shr {sign_r}, 15')          # sign_r = 0 or 1
                self._emit(f'    shr {dst}, {right_r}')      # logical shift
                sar_lbl = self._new_label('sar')
                self._emit(f'    test {sign_r}, {sign_r}')
                self._emit(f'    jz {sar_lbl}')              # was positive, done
                # was negative: fill upper N bits with 1
                # mask = ~(0xFFFF >> N) -> upper N bits are 1
                self._emit(f'    mov {mask_r}, 0xFFFF')
                self._emit(f'    shr {mask_r}, {right_r}')   # lower (16-N) bits are 1
                self._emit(f'    xor {mask_r}, 0xFFFF')      # invert -> upper N bits are 1
                self._emit(f'    or  {dst}, {mask_r}')       # set upper N bits
                self._label(sar_lbl)
                self._regs.free()   # mask_r
                self._regs.free()   # sign_r
        elif op in ('==', '!=', '<', '>', '<=', '>='):
            dst = self._gen_compare(op, left_r, right_r)
        else:
            raise CodegenError(f"Unknown binop: {op}")

        self._regs.free()  # free right_r
        return dst

    def _gen_compare(self, op: str, left_r: str, right_r: str) -> str:
        """Evaluate a comparison and return 0 or 1 in a register"""
        true_lbl = self._new_label('ct')
        end_lbl  = self._new_label('ce')
        dst = left_r

        self._emit(f'    sub r0, {left_r}, {right_r}')

        jmp_map = {
            '==': 'jz',  '!=': 'jnz',
            '<':  'jl',  '>':  'jnle',  # signed: jnle = NOT(<=) = >
            '<=': 'jle', '>=': 'jnl',   # signed: jnl  = NOT(<)  = >=
        }
        j = jmp_map[op]
        self._emit(f'    {j} {true_lbl}')
        self._emit(f'    mov {dst}, 0')
        self._emit(f'    jmp {end_lbl}')
        self._label(true_lbl)
        self._emit(f'    mov {dst}, 1')
        self._label(end_lbl)
        self._regs.free()  # right_r
        return dst

    def _gen_short_circuit(self, expr: BinOp, is_or: bool) -> str:
        end_lbl = self._new_label('sc')
        dst = self._regs.alloc()

        left_r = self._gen_expr(expr.left)
        self._emit(f'    mov {dst}, {left_r}')
        self._regs.free()

        self._emit(f'    test {dst}, {dst}')
        if is_or:
            self._emit(f'    jnz {end_lbl}')  # OR: already true, short-circuit
        else:
            self._emit(f'    jz {end_lbl}')   # AND: already false, short-circuit

        right_r = self._gen_expr(expr.right)
        self._emit(f'    mov {dst}, {right_r}')
        self._regs.free()

        self._label(end_lbl)
        # normalize to 0/1
        true_lbl = self._new_label('sct')
        end2_lbl = self._new_label('sce')
        self._emit(f'    test {dst}, {dst}')
        self._emit(f'    jnz {true_lbl}')
        self._emit(f'    mov {dst}, 0')
        self._emit(f'    jmp {end2_lbl}')
        self._label(true_lbl)
        self._emit(f'    mov {dst}, 1')
        self._label(end2_lbl)
        return dst

    def _gen_unary(self, expr: UnaryOp) -> str:
        op = expr.op

        if op == '-':
            r = self._gen_expr(expr.operand)
            self._emit(f'    sub {r}, r0, {r}')  # r0 = 0x20000000, ALU sees 0
            return r

        if op == '~':
            r = self._gen_expr(expr.operand)
            self._emit(f'    xor {r}, 0xFFFF')
            return r

        if op == '!':
            r = self._gen_expr(expr.operand)
            true_lbl = self._new_label('nt')
            end_lbl  = self._new_label('ne')
            self._emit(f'    test {r}, {r}')
            self._emit(f'    jz {true_lbl}')
            self._emit(f'    mov {r}, 0')
            self._emit(f'    jmp {end_lbl}')
            self._label(true_lbl)
            self._emit(f'    mov {r}, 1')
            self._label(end_lbl)
            return r

        if op == '&':
            return self._gen_addr(expr.operand)

        if op == '*':
            ptr_r = self._gen_expr(expr.operand)
            self._emit(f'    ld {ptr_r}, {ptr_r}')
            return ptr_r

        if op in ('++pre', '--pre'):
            addr_r  = self._gen_addr(expr.operand)
            val_r   = self._regs.alloc()
            op_type = expr.operand.ctype
            step    = _ptr_step(op_type)
            self._emit(f'    ld {val_r}, {addr_r}')
            self._emit(f'    {"add" if op == "++pre" else "sub"} {val_r}, {step}')
            self._emit(f'    st {val_r}, {addr_r}')
            self._regs.free()  # addr_r
            return val_r

        if op in ('++post', '--post'):
            addr_r  = self._gen_addr(expr.operand)
            old_r   = self._regs.alloc()
            op_type = expr.operand.ctype
            step    = _ptr_step(op_type)
            self._emit(f'    ld {old_r}, {addr_r}')
            tmp_r   = self._regs.alloc()
            self._emit(f'    mov {tmp_r}, {old_r}')
            self._emit(f'    {"add" if op == "++post" else "sub"} {tmp_r}, {step}')
            self._emit(f'    st {tmp_r}, {addr_r}')
            self._regs.free()  # tmp_r
            self._regs.free()  # addr_r
            return old_r

        raise CodegenError(f"Unknown unary op: {op}")

    def _gen_assign(self, expr: Assign) -> str:
        op = expr.op

        if op == '=':
            val_r = self._gen_expr(expr.value)
            self._gen_store(val_r, expr.target)
            return val_r

        # compound assignment (+=, -= etc.) -> load, operate, store
        cur_r = self._gen_expr(expr.target)
        rhs_r = self._gen_expr(expr.value)

        target_type = expr.target.ctype

        if op in ('+=', '-='):
            # Scale RHS by element size for pointer arithmetic
            if isinstance(target_type, (CPointer, CArray)):
                base = target_type.base if hasattr(target_type, 'base') else None
                elem_sz = base.size() if base else 1
                if elem_sz > 1:
                    self._emit(f'    mul {rhs_r}, {rhs_r}, {elem_sz}')
            asm_op = 'add' if op == '+=' else 'sub'
            self._emit(f'    {asm_op} {cur_r}, {rhs_r}')
        elif op == '&=':
            self._emit(f'    and {cur_r}, {rhs_r}')
        elif op == '|=':
            self._emit(f'    or  {cur_r}, {rhs_r}')
        elif op == '^=':
            self._emit(f'    xor {cur_r}, {rhs_r}')
        elif op == '*=':
            self._emit(f'    mul {cur_r}, {cur_r}, {rhs_r}')
        elif op == '/=':
            div_fn = '__udiv' if self._is_unsigned(target_type) else '__sdiv'
            self._emit(f'    mov r1, {cur_r}')
            self._emit(f'    mov r2, {rhs_r}')
            self._emit(f'    jmp r31, {div_fn}')
            self._emit(f'    mov {cur_r}, r1')
        self._regs.free()  # rhs_r
        self._gen_store(cur_r, expr.target)
        return cur_r

    def _gen_call(self, expr: Call) -> str:
        # ── va builtins ──────────────────────────────────────────────────────
        if isinstance(expr.func, Ident):
            name = expr.func.name

            if name == 'va_start':
                # va_start(ap[, last]) : ap = SP + va_offset
                # va_offset = frame_size + n_stack_params (past params 5+)
                ap_addr = self._gen_addr(expr.args[0])
                va_r = self._regs.alloc()
                fs = getattr(self, '_va_offset', 0)
                if fs:
                    self._emit(f'    add {va_r}, {SP}, {fs}')
                else:
                    self._emit(f'    mov {va_r}, {SP}')
                self._emit(f'    st {va_r}, {ap_addr}')
                self._regs.free()   # va_r
                self._regs.free()   # ap_addr
                return self._regs.alloc()   # discarded return value

            if name == 'va_arg':
                # va_arg(ap[, type]) : val = *ap; ap++
                ap_addr = self._gen_addr(expr.args[0])
                ptr_r = self._regs.alloc()
                self._emit(f'    ld {ptr_r}, {ap_addr}')   # ptr = *(&ap) = ap
                val_r = self._regs.alloc()
                self._emit(f'    ld {val_r}, {ptr_r}')      # val = *ptr
                self._emit(f'    add {ptr_r}, 1')
                self._emit(f'    st {ptr_r}, {ap_addr}')    # ap++
                self._regs.free()   # ptr_r
                self._regs.free()   # ap_addr
                return val_r

            if name == 'va_end':
                return self._regs.alloc()   # no-op

        # ── regular / variadic function call ─────────────────────────────────
        is_variadic = getattr(expr, '_variadic', False)
        n_fixed     = getattr(expr, '_n_fixed',  len(expr.args))

        all_fixed      = expr.args[:n_fixed]
        variadic_extra = expr.args[n_fixed:]

        reg_args    = all_fixed[:4]
        stack_fixed = all_fixed[4:]

        # Snapshot outer live regs BEFORE evaluating any args.
        # These are caller-saved regs that must survive the call.
        # Only r5-r13 (CALLER_TMP_REGS) need saving; r14-r17 are callee-saved
        # and will be preserved by the callee's own prologue/epilogue.
        outer_cp   = self._regs.checkpoint()
        n_outer    = min(outer_cp, len(CALLER_TMP_REGS))

        # evaluate arguments
        reg_regs         = [self._gen_expr(a) for a in reg_args]
        stack_fixed_regs = [self._gen_expr(a) for a in stack_fixed]
        variadic_regs    = [self._gen_expr(a) for a in variadic_extra]

        # Resolve function pointer before saving outer regs (if indirect call)
        fptr = None
        if not isinstance(expr.func, Ident):
            fptr = self._gen_expr(expr.func)

        # Save outer caller-saved regs to a temporary area below SP.
        # Stack layout after saves (before stack args):
        #   SP-1 = CALLER_TMP_REGS[0]  (oldest, saved last = highest address)
        #   ...
        #   SP-n_outer = CALLER_TMP_REGS[n_outer-1]  (newest, lowest address)
        for i in range(n_outer):
            self._emit(f'    sub {SP}, 1')
            self._emit(f'    st {CALLER_TMP_REGS[i]}, {SP}, 0')

        # push stack arguments in reverse order
        all_stack_regs = stack_fixed_regs + variadic_regs
        for r in reversed(all_stack_regs):
            self._emit(f'    sub {SP}, 1')
            self._emit(f'    st {r}, {SP}, 0')

        # place fixed args into r1..r4
        for i, r in enumerate(reg_regs):
            if r != ARG_REGS[i]:
                self._emit(f'    mov {ARG_REGS[i]}, {r}')

        # call
        if fptr is not None:
            self._emit(f'    jmp {LR}, {fptr}')
        else:
            self._emit(f'    jmp {LR}, {expr.func.name}')

        # caller cleans up stack arguments
        total_stack = len(stack_fixed) + len(variadic_extra)
        if total_stack:
            self._emit(f'    add {SP}, {total_stack}')

        # Restore outer caller-saved regs (in reverse save order)
        for i in range(n_outer - 1, -1, -1):
            self._emit(f'    ld {CALLER_TMP_REGS[i]}, {SP}, 0')
            self._emit(f'    add {SP}, 1')

        # Capture return value; arg regs are no longer needed
        self._regs.restore(outer_cp)
        dst = self._regs.alloc()
        if dst != RET_REG:
            self._emit(f'    mov {dst}, {RET_REG}')
        return dst

    def _gen_index(self, expr: Index) -> str:
        addr_r = self._gen_addr(expr)
        self._emit(f'    ld {addr_r}, {addr_r}')
        return addr_r
