"""
C to R316 Compiler - Code Generator
AST → TPTASM R316 Assembly

ABI:
  r1..r4  : arguments / return values (r1=lo, r2=hi for long)
  r5..r13 : caller-saved temporaries
  r14..r29: callee-saved
  r30 (sp): stack pointer (grows downward)
  r31 (lr): link register

Stack frame:
  [sp+0 .. sp+local_size-1] : local variables
  [sp-1] : saved lr (non-leaf functions)

Register allocation strategy:
  Simple linear allocator - temporaries assigned from r5..r13 in order
  Spill to stack when registers are exhausted
"""

from .ast_nodes import *
import sys


# ABI constants
SP = 'r30'
LR = 'r31'
ARG_REGS  = ['r1', 'r2', 'r3', 'r4']
RET_REG   = 'r1'
RET_REG_H = 'r2'
TMP_REGS  = ['r5', 'r6', 'r7', 'r8', 'r9', 'r10', 'r11', 'r12', 'r13']


class CodegenError(Exception):
    pass


class RegAlloc:
    """Simple linear temporary register allocator"""
    def __init__(self):
        self._used = 0
        self._spill_offset = 0

    def alloc(self) -> str:
        if self._used < len(TMP_REGS):
            r = TMP_REGS[self._used]
            self._used += 1
            return r
        raise CodegenError("Ran out of temporary registers (spill not yet implemented)")

    def free(self):
        if self._used > 0:
            self._used -= 1

    def checkpoint(self) -> int:
        return self._used

    def restore(self, cp: int):
        self._used = cp


class Codegen:
    def __init__(self):
        self.out: list[str]  = []
        self._label_cnt      = 0
        self._string_data: list[tuple[str, list[int]]] = []
        self._global_vars: list[VarDecl] = []
        self._loop_break_stack: list[str]    = []
        self._loop_cont_stack:  list[str]    = []
        self._regs = RegAlloc()
        self._local_vars: dict[str, tuple[int, CType]] = {}  # name → (sp_offset, type)
        self._param_regs: dict[str, str] = {}   # name → register
        self._local_size = 0
        self._current_ret_type: CType = CVoid()

    # ── Output Helpers ─────────────────────────────────────────────────────────────

    def _emit(self, line: str):
        self.out.append(line)

    def _label(self, name: str):
        self._emit(f'{name}:')

    def _new_label(self, prefix='L') -> str:
        self._label_cnt += 1
        return f'._c2r_{prefix}_{self._label_cnt}'

    def _comment(self, txt: str):
        self._emit(f'    ; {txt}')

    # ── Top-Level ───────────────────────────────────────────────────────────────

    def generate(self, prog: Program) -> str:
        self._emit('; Generated by C→R316 compiler')
        self._emit('%include "common"')
        self._emit('')

        # collect global variables / function declarations first
        funcs = []
        for decl in prog.decls:
            if isinstance(decl, FuncDecl):
                funcs.append(decl)
            elif isinstance(decl, VarDecl):
                self._global_vars.append(decl)

        # runtime entry point
        self._emit('; ── entry point ──')
        self._emit('start:')
        self._emit(f'    mov {SP}, 0x800')
        self._emit(f'    jmp {LR}, __term_init')
        self._emit(f'    jmp {LR}, main')
        self._emit(f'    hlt')
        self._emit('')

        # generate function code
        for func in funcs:
            if func.body is not None:
                self._gen_func(func)

        # global variable data
        if self._global_vars:
            self._emit('; ── global variables ──')
            for v in self._global_vars:
                self._gen_global_var(v)

        # string literals
        if self._string_data:
            self._emit('')
            self._emit('; ── string literals ──')
            for label, chars in self._string_data:
                data = ', '.join(str(c) for c in chars) + ', 0'
                self._emit(f'{label}: dw {data}')

        return '\n'.join(self.out)

    # ── Global Variables ─────────────────────────────────────────────────────────────

    def _gen_global_var(self, v: VarDecl):
        if isinstance(v.ctype, CArray):
            size = v.ctype.size()
            if v.init is None:
                self._emit(f'{v.name}: dw {", ".join(["0"] * size)}')
            else:
                # array initializer not fully supported: fill with 0
                self._emit(f'{v.name}: dw {", ".join(["0"] * size)}')
        else:
            val = 0
            if isinstance(v.init, IntLit):
                val = v.init.value & 0xFFFF
            elif isinstance(v.init, CharLit):
                val = v.init.value & 0xFF
            self._emit(f'{v.name}: dw {val}')

    # ── Functions ─────────────────────────────────────────────────────────────────

    def _gen_func(self, func: FuncDecl):
        self._comment(f'function {func.name}')
        self._label(func.name)

        # initialize local state
        self._local_vars  = {}
        self._param_regs  = {}
        self._local_size  = getattr(func, '_local_size', 0)
        self._current_ret_type = func.ret_type

        # parameters: incoming r1..r4 saved to stack
        param_count = len(func.params)
        # save lr too for non-leaf functions
        is_leaf = self._is_leaf(func.body)

        frame_size = self._local_size
        if not is_leaf:
            frame_size += 1  # slot for saved lr

        if frame_size > 0:
            self._emit(f'    sub {SP}, {frame_size}')

        if not is_leaf:
            lr_slot = self._local_size  # sp + local_size
            self._emit(f'    st {LR}, {SP}, {lr_slot}')

        # parameters to stack or registers
        # simplified: keep parameters in r1..r4, map by name
        for i, param in enumerate(func.params):
            if i < len(ARG_REGS):
                self._param_regs[param.name] = ARG_REGS[i]
            # TODO: parameters beyond 4 passed via stack

        # rebuild local variable offsets (semantic already set them, but managed here too)
        offset = 0
        for stmt in func.body.stmts:
            offset = self._collect_locals(stmt, offset)

        # set epilogue label in advance (referenced by return statements)
        ret_label = f'{func.name}._ret'
        self._ret_label = ret_label

        # generate body
        self._regs.restore(0)
        self._gen_block(func.body)

        # epilogue
        self._label(ret_label)

        if not is_leaf:
            self._emit(f'    ld {LR}, {SP}, {lr_slot}')

        if frame_size > 0:
            self._emit(f'    add {SP}, {frame_size}')

        self._emit(f'    jmp {LR}')
        self._emit('')

    def _collect_locals(self, stmt: Stmt, offset: int) -> int:
        if isinstance(stmt, DeclStmt):
            d = stmt.decl
            size = max(d.ctype.size(), 1)
            self._local_vars[d.name] = (offset, d.ctype)
            return offset + size
        if isinstance(stmt, Block):
            for s in stmt.stmts:
                offset = self._collect_locals(s, offset)
        if isinstance(stmt, IfStmt):
            offset = self._collect_locals(stmt.then, offset)
            if stmt.else_:
                offset = self._collect_locals(stmt.else_, offset)
        if isinstance(stmt, (WhileStmt,)):
            offset = self._collect_locals(stmt.body, offset)
        if isinstance(stmt, ForStmt):
            if stmt.init:
                offset = self._collect_locals(stmt.init, offset)
            offset = self._collect_locals(stmt.body, offset)
        return offset

    def _is_leaf(self, block: Optional[Block]) -> bool:
        """leaf function if it contains no calls"""
        if block is None:
            return True
        return not self._has_call(block)

    def _has_call(self, node) -> bool:
        if isinstance(node, Call):
            return True
        if isinstance(node, (Block, ForStmt, WhileStmt)):
            stmts = getattr(node, 'stmts', [])
            if not stmts:
                stmts = []
                for attr in ('init', 'cond', 'step', 'body'):
                    v = getattr(node, attr, None)
                    if v: stmts.append(v)
            return any(self._has_call(s) for s in stmts)
        for attr in vars(node).values() if hasattr(node, '__dict__') else []:
            if isinstance(attr, Node) and self._has_call(attr):
                return True
            if isinstance(attr, list):
                for item in attr:
                    if isinstance(item, Node) and self._has_call(item):
                        return True
        return False

    # ── Statement Code Generation ────────────────────────────────────────────────────────

    def _gen_block(self, block: Block):
        for stmt in block.stmts:
            self._gen_stmt(stmt)

    def _gen_stmt(self, stmt: Stmt):
        self._regs.restore(0)

        if isinstance(stmt, Block):
            self._gen_block(stmt)

        elif isinstance(stmt, DeclStmt):
            d = stmt.decl
            if d.init is not None:
                r = self._gen_expr(d.init)
                off, _ = self._local_vars[d.name]
                self._emit(f'    st {r}, {SP}, {off}')

        elif isinstance(stmt, ExprStmt):
            self._gen_expr(stmt.expr)

        elif isinstance(stmt, IfStmt):
            self._gen_if(stmt)

        elif isinstance(stmt, WhileStmt):
            self._gen_while(stmt)

        elif isinstance(stmt, ForStmt):
            self._gen_for(stmt)

        elif isinstance(stmt, ReturnStmt):
            if stmt.expr is not None:
                r = self._gen_expr(stmt.expr)
                if r != RET_REG:
                    self._emit(f'    mov {RET_REG}, {r}')
            self._emit(f'    jmp {self._ret_label}')

        elif isinstance(stmt, BreakStmt):
            if not self._loop_break_stack:
                raise CodegenError("break outside loop")
            self._emit(f'    jmp {self._loop_break_stack[-1]}')

        elif isinstance(stmt, ContinueStmt):
            if not self._loop_cont_stack:
                raise CodegenError("continue outside loop")
            self._emit(f'    jmp {self._loop_cont_stack[-1]}')

    def _gen_if(self, stmt: IfStmt):
        else_lbl = self._new_label('else')
        end_lbl  = self._new_label('endif')

        cond_r = self._gen_expr(stmt.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._emit(f'    jz {else_lbl}')

        self._gen_stmt(stmt.then)
        if stmt.else_:
            self._emit(f'    jmp {end_lbl}')
        self._label(else_lbl)
        if stmt.else_:
            self._gen_stmt(stmt.else_)
            self._label(end_lbl)

    def _gen_while(self, stmt: WhileStmt):
        cond_lbl = self._new_label('wcond')
        body_lbl = self._new_label('wbody')
        end_lbl  = self._new_label('wend')

        self._loop_break_stack.append(end_lbl)
        self._loop_cont_stack.append(cond_lbl)

        self._label(cond_lbl)
        cond_r = self._gen_expr(stmt.cond)
        self._emit(f'    test {cond_r}, {cond_r}')
        self._emit(f'    jz {end_lbl}')

        self._gen_stmt(stmt.body)
        self._emit(f'    jmp {cond_lbl}')
        self._label(end_lbl)

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    def _gen_for(self, stmt: ForStmt):
        cond_lbl = self._new_label('fcond')
        step_lbl = self._new_label('fstep')
        end_lbl  = self._new_label('fend')

        if stmt.init:
            self._gen_stmt(stmt.init)

        self._loop_break_stack.append(end_lbl)
        self._loop_cont_stack.append(step_lbl)

        self._label(cond_lbl)
        if stmt.cond:
            cond_r = self._gen_expr(stmt.cond)
            self._emit(f'    test {cond_r}, {cond_r}')
            self._emit(f'    jz {end_lbl}')

        self._gen_stmt(stmt.body)

        self._label(step_lbl)
        if stmt.step:
            self._gen_expr(stmt.step)

        self._emit(f'    jmp {cond_lbl}')
        self._label(end_lbl)

        self._loop_break_stack.pop()
        self._loop_cont_stack.pop()

    # ── Expression Code Generation → returns result register ───────────────────────────────

    def _gen_expr(self, expr: Expr) -> str:
        """Evaluate expression and return the register name holding the result"""

        if isinstance(expr, IntLit):
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {expr.value & 0xFFFF}')
            return r

        if isinstance(expr, CharLit):
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {expr.value & 0xFF}')
            return r

        if isinstance(expr, StringLit):
            self._label_cnt += 1
            lbl = f'_cstr_{self._label_cnt}'
            expr.label = lbl
            self._string_data.append((lbl, expr.chars))
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {lbl}')
            return r

        if isinstance(expr, Ident):
            return self._gen_load_ident(expr)

        if isinstance(expr, BinOp):
            return self._gen_binop(expr)

        if isinstance(expr, UnaryOp):
            return self._gen_unary(expr)

        if isinstance(expr, Assign):
            return self._gen_assign(expr)

        if isinstance(expr, Call):
            return self._gen_call(expr)

        if isinstance(expr, Index):
            return self._gen_index(expr)

        if isinstance(expr, Cast):
            r = self._gen_expr(expr.expr)
            # simple type cast: mask if needed
            if isinstance(expr.to_type, CChar):
                self._emit(f'    and {r}, 0xFF')
            return r

        if isinstance(expr, SizeOf):
            r = self._regs.alloc()
            if isinstance(expr.target, CType):
                self._emit(f'    mov {r}, {expr.target.size()}')
            else:
                sz = expr.target.ctype.size() if expr.target.ctype else 1
                self._emit(f'    mov {r}, {sz}')
            return r

        raise CodegenError(f"Unhandled expression: {type(expr)}")

    def _gen_load_ident(self, expr: Ident) -> str:
        name = expr.name
        # parameter
        if name in self._param_regs:
            return self._param_regs[name]
        # local variable
        if name in self._local_vars:
            off, ctype = self._local_vars[name]
            r = self._regs.alloc()
            self._emit(f'    ld {r}, {SP}, {off}')
            return r
        # global variable / function
        r = self._regs.alloc()
        if isinstance(expr.ctype, CFunction):
            self._emit(f'    mov {r}, {name}')
        else:
            self._emit(f'    ld {r}, {name}')
        return r

    def _gen_addr(self, expr: Expr) -> str:
        """Load the address of an lvalue into a register and return it"""
        if isinstance(expr, Ident):
            name = expr.name
            if name in self._local_vars:
                off, _ = self._local_vars[name]
                r = self._regs.alloc()
                self._emit(f'    add {r}, {SP}, {off}' if off else f'    mov {r}, {SP}')
                return r
            r = self._regs.alloc()
            self._emit(f'    mov {r}, {name}')
            return r

        if isinstance(expr, Index):
            arr_r  = self._gen_expr(expr.array)
            idx_r  = self._gen_expr(expr.index)
            elem_sz = expr.ctype.size() if expr.ctype else 1
            if elem_sz > 1:
                self._emit(f'    mul {idx_r}, {idx_r}, {elem_sz}')
            self._emit(f'    add {arr_r}, {idx_r}')
            self._regs.free()  # free idx_r
            return arr_r

        if isinstance(expr, UnaryOp) and expr.op == '*':
            return self._gen_expr(expr.operand)

        raise CodegenError(f"Cannot take address of {type(expr)}")

    def _gen_store(self, val_r: str, target: Expr):
        """Store the value in val_r into the target lvalue"""
        if isinstance(target, Ident):
            name = target.name
            if name in self._local_vars:
                off, _ = self._local_vars[name]
                self._emit(f'    st {val_r}, {SP}, {off}')
                return
            self._emit(f'    st {val_r}, {name}')
            return
        if isinstance(target, Index):
            addr_r = self._gen_addr(target)
            self._emit(f'    st {val_r}, {addr_r}')
            self._regs.free()
            return
        if isinstance(target, UnaryOp) and target.op == '*':
            ptr_r = self._gen_expr(target.operand)
            self._emit(f'    st {val_r}, {ptr_r}')
            self._regs.free()
            return
        raise CodegenError(f"Cannot store into {type(target)}")

    def _gen_binop(self, expr: BinOp) -> str:
        op = expr.op

        # short-circuit evaluation
        if op == '&&':
            return self._gen_short_circuit(expr, False)
        if op == '||':
            return self._gen_short_circuit(expr, True)

        left_r  = self._gen_expr(expr.left)
        right_r = self._gen_expr(expr.right)
        dst     = left_r   # overwrite left with result

        if op == '+':
            self._emit(f'    add {dst}, {right_r}')
        elif op == '-':
            self._emit(f'    sub {dst}, {right_r}')
        elif op == '*':
            self._emit(f'    mul {dst}, {dst}, {right_r}')
        elif op == '/':
            # division: call runtime __udiv
            self._emit(f'    mov r1, {dst}')
            self._emit(f'    mov r2, {right_r}')
            self._emit(f'    jmp r31, __udiv')
            dst = self._regs.alloc()
            self._emit(f'    mov {dst}, r1')
        elif op == '%':
            self._emit(f'    mov r1, {dst}')
            self._emit(f'    mov r2, {right_r}')
            self._emit(f'    jmp r31, __umod')
            dst = self._regs.alloc()
            self._emit(f'    mov {dst}, r1')
        elif op == '&':
            self._emit(f'    and {dst}, {right_r}')
        elif op == '|':
            self._emit(f'    or  {dst}, {right_r}')
        elif op == '^':
            self._emit(f'    xor {dst}, {right_r}')
        elif op == '<<':
            self._emit(f'    shl {dst}, {right_r}')
        elif op == '>>':
            self._emit(f'    shr {dst}, {right_r}')
        elif op in ('==', '!=', '<', '>', '<=', '>='):
            dst = self._gen_compare(op, left_r, right_r)
        else:
            raise CodegenError(f"Unknown binop: {op}")

        self._regs.free()  # free right_r
        return dst

    def _gen_compare(self, op: str, left_r: str, right_r: str) -> str:
        """Return comparison result as 0/1 in a register"""
        true_lbl = self._new_label('ct')
        end_lbl  = self._new_label('ce')
        dst = left_r

        self._emit(f'    sub r0, {left_r}, {right_r}')

        jmp_map = {
            '==': 'jz',  '!=': 'jnz',
            '<':  'jl',  '>':  'jnl',   # signed
            '<=': 'jle', '>=': 'jnle',
        }
        j = jmp_map[op]
        self._emit(f'    {j} {true_lbl}')
        self._emit(f'    mov {dst}, 0')
        self._emit(f'    jmp {end_lbl}')
        self._label(true_lbl)
        self._emit(f'    mov {dst}, 1')
        self._label(end_lbl)
        self._regs.free()  # right_r
        return dst

    def _gen_short_circuit(self, expr: BinOp, is_or: bool) -> str:
        end_lbl = self._new_label('sc')
        dst = self._regs.alloc()

        left_r = self._gen_expr(expr.left)
        self._emit(f'    mov {dst}, {left_r}')
        self._regs.free()

        self._emit(f'    test {dst}, {dst}')
        if is_or:
            self._emit(f'    jnz {end_lbl}')  # OR: already true, done
        else:
            self._emit(f'    jz {end_lbl}')   # AND: already false, done

        right_r = self._gen_expr(expr.right)
        self._emit(f'    mov {dst}, {right_r}')
        self._regs.free()

        self._label(end_lbl)
        # normalize to 0/1
        true_lbl = self._new_label('sct')
        end2_lbl = self._new_label('sce')
        self._emit(f'    test {dst}, {dst}')
        self._emit(f'    jnz {true_lbl}')
        self._emit(f'    mov {dst}, 0')
        self._emit(f'    jmp {end2_lbl}')
        self._label(true_lbl)
        self._emit(f'    mov {dst}, 1')
        self._label(end2_lbl)
        return dst

    def _gen_unary(self, expr: UnaryOp) -> str:
        op = expr.op

        if op == '-':
            r = self._gen_expr(expr.operand)
            self._emit(f'    sub {r}, r0, {r}')  # r0 = 0x20000000, ALU sees 0
            return r

        if op == '~':
            r = self._gen_expr(expr.operand)
            self._emit(f'    xor {r}, 0xFFFF')
            return r

        if op == '!':
            r = self._gen_expr(expr.operand)
            true_lbl = self._new_label('nt')
            end_lbl  = self._new_label('ne')
            self._emit(f'    test {r}, {r}')
            self._emit(f'    jz {true_lbl}')
            self._emit(f'    mov {r}, 0')
            self._emit(f'    jmp {end_lbl}')
            self._label(true_lbl)
            self._emit(f'    mov {r}, 1')
            self._label(end_lbl)
            return r

        if op == '&':
            return self._gen_addr(expr.operand)

        if op == '*':
            ptr_r = self._gen_expr(expr.operand)
            self._emit(f'    ld {ptr_r}, {ptr_r}')
            return ptr_r

        if op in ('++pre', '--pre'):
            addr_r = self._gen_addr(expr.operand)
            val_r  = self._regs.alloc()
            self._emit(f'    ld {val_r}, {addr_r}')
            self._emit(f'    {"add" if op == "++pre" else "sub"} {val_r}, 1')
            self._emit(f'    st {val_r}, {addr_r}')
            self._regs.free()  # addr_r
            return val_r

        if op in ('++post', '--post'):
            addr_r = self._gen_addr(expr.operand)
            old_r  = self._regs.alloc()
            self._emit(f'    ld {old_r}, {addr_r}')
            tmp_r  = self._regs.alloc()
            self._emit(f'    mov {tmp_r}, {old_r}')
            self._emit(f'    {"add" if op == "++post" else "sub"} {tmp_r}, 1')
            self._emit(f'    st {tmp_r}, {addr_r}')
            self._regs.free()  # tmp_r
            self._regs.free()  # addr_r
            return old_r

        raise CodegenError(f"Unknown unary op: {op}")

    def _gen_assign(self, expr: Assign) -> str:
        op = expr.op

        if op == '=':
            val_r = self._gen_expr(expr.value)
            self._gen_store(val_r, expr.target)
            return val_r

        # compound assignment (+=, -= etc.) → load, operate, store
        cur_r = self._gen_expr(expr.target)
        rhs_r = self._gen_expr(expr.value)
        binop_map = {
            '+=': 'add', '-=': 'sub', '&=': 'and',
            '|=': 'or',  '^=': 'xor',
        }
        if op in binop_map:
            self._emit(f'    {binop_map[op]} {cur_r}, {rhs_r}')
        elif op == '*=':
            self._emit(f'    mul {cur_r}, {cur_r}, {rhs_r}')
        elif op == '/=':
            self._emit(f'    mov r1, {cur_r}')
            self._emit(f'    mov r2, {rhs_r}')
            self._emit(f'    jmp r31, __udiv')
            self._emit(f'    mov {cur_r}, r1')
        self._regs.free()  # rhs_r
        self._gen_store(cur_r, expr.target)
        return cur_r

    def _gen_call(self, expr: Call) -> str:
        # place arguments into r1..r4
        arg_regs_used = []
        for i, arg in enumerate(expr.args):
            r = self._gen_expr(arg)
            if i < len(ARG_REGS):
                if r != ARG_REGS[i]:
                    self._emit(f'    mov {ARG_REGS[i]}, {r}')
                arg_regs_used.append(ARG_REGS[i])

        # direct call by function name or pointer call
        if isinstance(expr.func, Ident):
            self._emit(f'    jmp {LR}, {expr.func.name}')
        else:
            fptr = self._gen_expr(expr.func)
            self._emit(f'    jmp {LR}, {fptr}')

        # return value is in r1
        dst = self._regs.alloc()
        if dst != RET_REG:
            self._emit(f'    mov {dst}, {RET_REG}')
        return dst

    def _gen_index(self, expr: Index) -> str:
        addr_r = self._gen_addr(expr)
        self._emit(f'    ld {addr_r}, {addr_r}')
        return addr_r
